#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

# check if can skip building zams model
if [ -n "$MESA_RUN_OPTIONAL" ]; then
   do_one inlist_zams_header zams.mod
fi

do_one inlist_diffusion_smoothness_header final.mod

