#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

cp standard_part1.mod part1.mod
do_one inlist_part2_header part2.mod
cp part2.mod standard_part2.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

