      SubroutineHappa
      Implicitreal*8(A-H,O-Z)
      PARAMETER(NVARS=3)
      include '../obj/nfreq_and_mzone.inc'
      PARAMETER(NYDIM=(NVARS+2*NFREQ)*Mzon,MAXDER=4)
      Parameter(Is=5)
      PARAMETER(NZ=3000000)
      Parameter(Nstage=28,Natom=15)
      PARAMETER(KOMAX=80)
      LogicalLSYSTEM
      Parameter(LSystem=.FALSE.)
      Parameter(Pi=3.1415926535897932d+00,hPlanc=1.0545716280D-27,Cs=2.9979245800D+10,Boltzk=1.3806504000D-16,Avogar=6.0221417900D+2
     *3,AMbrun=1.6605387832D-24,AMelec=9.1093821500D-28,echarg=4.8032042700D-10,CG=6.6742800000D-08,CMS=1.9884000000D+33,RSol=6.9551
     *000000D+10,ULGR=1.4000000000D+01,UPURS=1.0000000000D+07,ULGPU=7.0000000000D+00,ULGEU=1.3000000000D+01,UPC=3.0856776000D+18,UTP
     *=1.0000000000D+05,URHO=1.0000000000D-06,CARAD=7.5657680191D-15,CSIGM=5.6704004778D-05,ERGEV=1.6021764864D-12,GRADeV=1.16045052
     *85D+04,RADC=7.5657680191D-02,CTOMP=4.0062048575D-01,CCAPS=2.6901213726D+01,CCAPZ=9.8964034725D+00)
      IntegerZn(Natom),ZnCo(Natom+1)
      DimensionAZ(Natom)
      Common/AZZn/AZ,Zn,ZnCo
      Common/NiAdap/tday,t_eve,XNifor(Mzon),AMeveNi,KNadap
      LOGICALFRST
      Parameter(Mfreq=130)
      Common/Kmzon/km,kmhap,Jac,FRST
      COMMON/STCOM1/t,H,HMIN,HMAX,EPS,N,METH,KFLAG,JSTART
      COMMON/YMAX/YMAX(NYDIM)
      COMMON/YSTIF/Y(NYDIM,MAXDER+1)
      COMMON/HNUSED/HUSED,NQUSED,NFUN,NJAC,NITER,NFAIL
      COMMON/HNT/HNT(7)
      PARAMETER(DELTA=1.d-05)
      PARAMETER(LICN=4*NZ,LIRN=2*NZ)
      LogicalNEEDBR
      COMMON/STJAC/THRMAT,HL,AJAC(LICN),IRN(LIRN),ICN(LICN),WJAC(NYDIM),FSAVE(NYDIM*2),IKEEP(5*NYDIM),IW(8*NYDIM),IDISP(11),NZMOD,NE
     *EDBR
      LOGICALCONV,CHNCND,SCAT,SEP
      COMMON/CUTOFF/FLOOR(NVARS+1),Wacc(NVARS+1),FitTau,TauTol,Rvis,CONV,CHNCND,SCAT,SEP
      LogicalLTHICK
      COMMON/THICK/LTHICK(Nfreq,Mzon)
      COMMON/CONVEC/UC(Mzon),YAINV(Mzon)
      COMMON/RAD/EDDJ(Mzon,Nfreq),EDDH(Mzon),HEDD(Nfreq),HEDRAD,CLIGHT,CKRAD,UFREQ,CFLUX,CCL,CLUM,CLUMF,CIMP,NTHICK(NFREQ),NTHNEW(NF
     *REQ),NCND,KRAD,NFRUS
      LOGICALEDTM
      COMMON/RADOLD/HEDOLD,HINEDD,EDTM
      Common/newedd/EddN(Mzon,Nfreq),HEdN(Nfreq),tfeau
      Common/oldedd/EddO(Mzon,Nfreq),HEdo(Nfreq),trlx
      Common/cnlast/Cnlast
      Common/Dhap/DHaphR(Mzon,Nfreq)
      COMMON/BAND/FREQ(NFREQ+1),FREQMN(NFREQ),WEIGHT(130),HAPPAL(NFREQ),HAPABSRON(NFREQ),HAPABS(NFREQ),DLOGNU(NFREQ)
      PARAMETER(NFRMIN=Nfreq/2)
      IntegerdLfrMax
      Common/observer/wH(Mfreq),cH(Mfreq),zerfr,Hcom(Mfreq),Hobs(Mfreq),freqob(Mfreq),dLfrMax
      Parameter(NP=15+15-1)
      Common/famu/fstatic(0:NP+1,Nfreq),fobs_corr(0:NP+1,Mfreq),fcom(0:NP+1,Mfreq),amustatic(0:NP+1)
      Common/rays/Pray(0:Np+1),fout(0:NP+1,Mfreq),abermu(0:NP+1),NmuNzon
      COMMON/LIM/Uplim,Haplim
      COMMON/AMM/DMIN,DM(Mzon),DMOUT,AMINI,AM(Mzon),AMOUT
      COMMON/Centr/RCE,Nzon
      Common/InEn/AMHT,EBurst,tBurst,tbeght
      COMMON/RADPUM/AMNI,XMNi,XNi,KmNick
      COMMON/RADGAM/FJgam(Mzon,2),toldg,tnewg
      COMMON/RADGlg/FJglog(Mzon,2)
      COMMON/CHEM/CHEM0(Mzon),RTphi(0:Mzon+1),EpsUq
      COMMON/REGIME/NREG(Mzon)
      doubleprecisionNRT
      COMMON/AQ/AQ,BQ,DRT,NRT
      COMMON/AZNUC/ACARB,ZCARB,ASI,ZSI,ANI,ZNI,QCSI,QSINI
      COMMON/QNRGYE/QNUC,RGASA,YELECT
      COMMON/CKN1/CK1,CK2,CFR,CRAP,CRAOLD
      LOGICALEVALJA,OLDJAC,BADSTE
      COMMON/EVAL/EVALJA,BADSTE,OLDJAC
      LogicalRadP
      COMMON/RadP/RadP
      COMMON/ARG/TP,PL,CHEM,LST,KENTR,JURS
      COMMON/RESULT/P,Egas,Sgas,ENG,CAPPA,PT,ET,ST,ENGT,CAPT,NZR
      COMMON/ABUND/XYZA,Yat(Natom)
      COMMON/AZ/AS,ZS,SCN
      COMMON/STR/PPL,EPL,SPL,ENGPL,CAPPL,CP,GAM,DA,DPE,DSE,DSP,BETgas
      COMMON/XELECT/XE,XET,XEPL,PE,Ycomp
      COMMON/URScap/Tpsqrt,Psicap,Scap,ScapT,ScapPl,ZMean,YZMean,ZMT,ZMPl,YZMT,YZMPl
      COMMON/BURNCC/CC,CCTP,CCPL,YDOT
      COMMON/ABarr/YABUN(Natom,Mzon)
      COMMON/UNSTL/UL,UPRESS,UE,UEPS,UCAP,UTIME,UV,UFLUX,UP
      COMMON/TAIL/KTAIL
      COMMON/UNINV/UPI,UEI
      COMMON/UNBSTL/UR,UM,UEPRI,ULGP,ULGE,ULGV,ULGTM,ULGEST,ULGFL,ULGCAP,ULGEPS
      COMMON/CONUR/EIT,DST,BBRCNR(5)
      COMMON/BAL/EL(MAXDER+1),YENTOT(MAXDER+1),ETOT0,ELVOL,ELSURF,ELTOT,TPSURF,HOLDBL,ELOST,EKO,RADBEG
      common/NSTEP/NSTEP,NDebug,MAXER,IOUT,NOUT
      common/CREAD/TAUOLD,NSTMAX,MBATCH,MAXORD
      common/debug/LfrDebug,Nperturb,Kbad
      REAL*8TPMAX(MAXDER+1),TQ(4)
      COMMON/TAU/TAU(Mzon+1),FLUX(Mzon)
      common/tauubvri/tauU(Mzon),tauB(Mzon),tauV(Mzon),tauR(Mzon),tauI(Mzon)
      COMMON/PHOT/XJPH,DMPH,RPH,TPH,PLPH,VPH,CHEMPH,GRVPH,HP,JPH
      PARAMETER(NFUNC=6)
      REAL*4WORK(Mzon+2,NFREQ),WRK(Mzon,4)
      REAL*8WRKX(Mzon),WORKX(Mzon+2)
      COMMON/STEPD/WRKX,WORKX,TPHOT,TEFF,WORK,WRK,NPHOT,NZM
      PARAMETER(TMCRIT=1.D-6,TPNSE=5.D0,EPGROW=0.02D0)
      Common/RUTP/Ry(Mzon),Uy(Mzon),Ty(Mzon),Press(Mzon),Rho(Mzon)
      COMMON/TOO/TOO,KO,KNTO,TO(KOMAX),STO(KOMAX),NTO(KOMAX)
      Parameter(Lcurdm=1000)
      RealTcurv
      IntegerNFRUSED
      REAL*8Flsave
      Common/Curve/tcurv(8,Lcurdm),Depos(Lcurdm),Flsave(MFREQ+1,Lcurdm),NFRUSED(Lcurdm),Lsaved
      LOGICALBEGRUN
      Common/BEGR/BEGRUN
      CHARACTER*80Model,Sumprf,Sumcur,Depfile,Flxfile
      COMMON/Files/Model,Sumprf,Sumcur,Depfile,Flxfile
      CHARACTER*1app
      LogicalGivdtl
      Common/ABGrap/NSTA,NSTB,TcurA,TcurB,Givdtl
      REAL*8MBOL,MU,MB,MV,MR,MI,MBOL1
      COMMON/COLOR/MBOL,MU,MB,MV,MR,MI,UMB,BMV,MBOL1,LubvU,LubvB,LubvV,LubvR,LubvI,Lyman
      COMMON/DETAIL/QRTarr(Mzon),UUarr(Mzon),ArrLum(Mzon),Acc(Mzon)
      Common/XYZ/XA,YA,URM
      Character*80Opafile
      real*4hptabab,hptababron,hptabsc,hpsavsc
      Common/Opsave/hpsavsc(Nfreq,14,14,Mzon/(Mzon/50)+1,6)
      Common/OpBand/TpTab(14),RhoTab(14),STab(6),Wavel(Nfreq),YATab(Natom),hptabab(Nfreq,14,14,Mzon/(Mzon/50)+1,2),hptababron(Nfreq,
     *14,14,Mzon/(Mzon/50)+1,2),hptabsc(Nfreq,14,14,Mzon/(Mzon/50)+1,2),Msta,Nrho,Ntp,im
      real*4hpbanab1(Nfreq,14,14,Mzon/(Mzon/50)+1),hpbanabron1(Nfreq,14,14,Mzon/(Mzon/50)+1),hpbansc1(Nfreq,14,14,Mzon/(Mzon/50)+1),
     *hpbanab2(Nfreq,14,14,Mzon/(Mzon/50)+1),hpbanabron2(Nfreq,14,14,Mzon/(Mzon/50)+1),hpbansc2(Nfreq,14,14,Mzon/(Mzon/50)+1)
      Equivalence(hptabab(1,1,1,1,1),hpbanab1(1,1,1,1)),(hptababron(1,1,1,1,1),hpbanabron1(1,1,1,1)),(hptabsc(1,1,1,1,1),hpbansc1(1,
     *1,1,1)),(hptabab(1,1,1,1,2),hpbanab2(1,1,1,1)),(hptababron(1,1,1,1,2),hpbanabron2(1,1,1,1)),(hptabsc(1,1,1,1,2),hpbansc2(1,1,1
     *,1))
      Common/tintrp/stmlog(6),tdlog,thaplog1,thaplog2,istold,Opafile
      Common/dumfreq/dumFreq(Nfreq+1),dumFreqmn(Nfreq),dumwavel(Nfreq)
      Parameter(DUSTK=1.d-03,TpDust=0.012d0,Cneutr=0.020D0)
      Integeri,j
      Real*8xx,yy,Fix1,Fix2,Tab00,Tab01,Tab10,Tab11
      DimensionFixtab(2),Fixtsc(2)
      Fun(z,tabz1,tabz2,fun1,fun2)=fun1-(fun1-fun2)*((z-tabz1)/(tabz2-tabz1))
      xx=Log(Pl*Urho)
      yy=Log(Tp*Utp)
      xx=max(xx,RhoTab(1))
      xx=min(xx,RhoTab(14))
      yy=max(yy,TpTab(1))
      yy=min(yy,TpTab(14))
      im=(kmhap-1)/(Mzon/50)+1
      im=min(im,mzon/(Mzon/50))
      i=INT((xx-RhoTab(1))/(RhoTab(2)-RhoTab(1)))+1
      i=Max0(1,i)
      i=Min0(14-1,i)
      j=INT((yy-TpTab(1))/(TpTab(2)-TpTab(1)))+1
      j=Max0(1,j)
      j=Min0(14-1,j)
      DO09999L=1,NFREQ
      IF(.NOT.(abs(Knadap).EQ.4.OR.abs(Knadap).EQ.5))GOTO09996
      DO09993iis=1,2
      Tab00=hptabab(l,j,i,im,iis)
      Tab01=hptabab(l,j,i+1,im,iis)
      Tab10=hptabab(l,j+1,i,im,iis)
      Tab11=hptabab(l,j+1,i+1,im,iis)
      Fix1=Fun(xx,RhoTab(i),RhoTab(i+1),Tab00,Tab01)
      Fix2=Fun(xx,RhoTab(i),RhoTab(i+1),Tab10,Tab11)
      Fixtab(iis)=Fun(yy,TpTab(j),TpTab(j+1),Fix1,Fix2)
      Tab00=hptabsc(l,j,i,im,iis)
      Tab01=hptabsc(l,j,i+1,im,iis)
      Tab10=hptabsc(l,j+1,i,im,iis)
      Tab11=hptabsc(l,j+1,i+1,im,iis)
      Fix1=Fun(xx,RhoTab(i),RhoTab(i+1),Tab00,Tab01)
      Fix2=Fun(xx,RhoTab(i),RhoTab(i+1),Tab10,Tab11)
      Fixtsc(iis)=Fun(yy,TpTab(j),TpTab(j+1),Fix1,Fix2)
09993 CONTINUE
      hbab=EXP(Fun(tdlog,thaplog1,thaplog2,Fixtab(1),Fixtab(2)))
      hbal=EXP(Fun(tdlog,thaplog1,thaplog2,Fixtsc(1),Fixtsc(2)))
      GOTO09994
09996 CONTINUE
      IF(.NOT.(abs(Knadap).EQ.6))GOTO09995
      iis=1
      Tab00=hptabab(l,j,i,im,iis)
      Tab01=hptabab(l,j,i+1,im,iis)
      Tab10=hptabab(l,j+1,i,im,iis)
      Tab11=hptabab(l,j+1,i+1,im,iis)
      Fix1=Fun(xx,RhoTab(i),RhoTab(i+1),Tab00,Tab01)
      Fix2=Fun(xx,RhoTab(i),RhoTab(i+1),Tab10,Tab11)
      Fixtab(iis)=Fun(yy,TpTab(j),TpTab(j+1),Fix1,Fix2)
      Tab00=hptabsc(l,j,i,im,iis)
      Tab01=hptabsc(l,j,i+1,im,iis)
      Tab10=hptabsc(l,j+1,i,im,iis)
      Tab11=hptabsc(l,j+1,i+1,im,iis)
      Fix1=Fun(xx,RhoTab(i),RhoTab(i+1),Tab00,Tab01)
      Fix2=Fun(xx,RhoTab(i),RhoTab(i+1),Tab10,Tab11)
      Fixtsc(iis)=Fun(yy,TpTab(j),TpTab(j+1),Fix1,Fix2)
      hbab=EXP(Fixtab(iis))
      hbal=EXP(Fixtsc(iis))
      GOTO09994
09995 CONTINUE
      write(*,*)'Use another routine for Happa!'
      stop64
09994 CONTINUE
      if(hbal.LT.0.d0.or.hbab.LT.0.d0.or.hbal.GT.1.d50.or.hbab.GT.1.d50)then
      write(40,'(2(a,i4),1p,4(a,e12.4))')' kmhap=',kmhap,' L=',L,'  hbal=',hbal,'  hbab=',hbab,'  Tp=',Tp,' pl=',pl
      write(40,*)' l j i im iis ',l,j,i,im,iis
      write(40,*)' tabs: ',tab00,tab01,tab10,tab11
      endif
      HAPPAL(L)=hbal
      If(Tp.LT.TpDust)Happal(L)=Happal(L)+DustK*(TpDust-Tp)**2*(UR*Urho)
      If(SCAT)Then
      HAPABS(L)=hbab
      If(Tp.LT.TpDust)Hapabs(L)=Hapabs(L)+DustK*(TpDust-Tp)**2*(UR*Urho)
      Else
      HAPABS(L)=HAPPAL(L)
      Endif
09999 CONTINUE
      Return
      End
