      SubroutineVOLEN(KMarg)
      Implicitreal*8(a-h,o-z)
      PARAMETER(NVARS=3)
      include '../obj/nfreq_and_mzone.inc'
      PARAMETER(NYDIM=(NVARS+2*NFREQ)*Mzon,MAXDER=4)
      Parameter(Is=5)
      PARAMETER(NZ=3000000)
      Parameter(Nstage=28,Natom=15)
      PARAMETER(KOMAX=80)
      LogicalLSYSTEM
      Parameter(LSystem=.FALSE.)
      Parameter(Pi=3.1415926535897932d+00,hPlanc=1.0545716280D-27,Cs=2.9979245800D+10,Boltzk=1.3806504000D-16,Avogar=6.0221417900D+2
     *3,AMbrun=1.6605387832D-24,AMelec=9.1093821500D-28,echarg=4.8032042700D-10,CG=6.6742800000D-08,CMS=1.9884000000D+33,RSol=6.9551
     *000000D+10,ULGR=1.4000000000D+01,UPURS=1.0000000000D+07,ULGPU=7.0000000000D+00,ULGEU=1.3000000000D+01,UPC=3.0856776000D+18,UTP
     *=1.0000000000D+05,URHO=1.0000000000D-06,CARAD=7.5657680191D-15,CSIGM=5.6704004778D-05,ERGEV=1.6021764864D-12,GRADeV=1.16045052
     *85D+04,RADC=7.5657680191D-02,CTOMP=4.0062048575D-01,CCAPS=2.6901213726D+01,CCAPZ=9.8964034725D+00)
      IntegerZn(Natom),ZnCo(Natom+1)
      DimensionAZ(Natom)
      Common/AZZn/AZ,Zn,ZnCo
      Common/NiAdap/tday,t_eve,XNifor(Mzon),AMeveNi,KNadap
      LOGICALFRST
      Parameter(Mfreq=130)
      Common/Kmzon/km,kmhap,Jac,FRST
      COMMON/STCOM1/t,H,HMIN,HMAX,EPS,N,METH,KFLAG,JSTART
      COMMON/YMAX/YMAX(NYDIM)
      COMMON/YSTIF/Y(NYDIM,MAXDER+1)
      COMMON/HNUSED/HUSED,NQUSED,NFUN,NJAC,NITER,NFAIL
      COMMON/HNT/HNT(7)
      PARAMETER(DELTA=1.d-05)
      PARAMETER(LICN=4*NZ,LIRN=2*NZ)
      LogicalNEEDBR
      COMMON/STJAC/THRMAT,HL,AJAC(LICN),IRN(LIRN),ICN(LICN),WJAC(NYDIM),FSAVE(NYDIM*2),IKEEP(5*NYDIM),IW(8*NYDIM),IDISP(11),NZMOD,NE
     *EDBR
      LOGICALCONV,CHNCND,SCAT,SEP
      COMMON/CUTOFF/FLOOR(NVARS+1),Wacc(NVARS+1),FitTau,TauTol,Rvis,CONV,CHNCND,SCAT,SEP
      LogicalLTHICK
      COMMON/THICK/LTHICK(Nfreq,Mzon)
      COMMON/CONVEC/UC(Mzon),YAINV(Mzon)
      COMMON/RAD/EDDJ(Mzon,Nfreq),EDDH(Mzon),HEDD(Nfreq),HEDRAD,CLIGHT,CKRAD,UFREQ,CFLUX,CCL,CLUM,CLUMF,CIMP,NTHICK(NFREQ),NTHNEW(NF
     *REQ),NCND,KRAD,NFRUS
      LOGICALEDTM
      COMMON/RADOLD/HEDOLD,HINEDD,EDTM
      Common/newedd/EddN(Mzon,Nfreq),HEdN(Nfreq),tfeau
      Common/oldedd/EddO(Mzon,Nfreq),HEdo(Nfreq),trlx
      Common/cnlast/Cnlast
      Common/Dhap/DHaphR(Mzon,Nfreq)
      COMMON/BAND/FREQ(NFREQ+1),FREQMN(NFREQ),WEIGHT(130),HAPPAL(NFREQ),HAPABSRON(NFREQ),HAPABS(NFREQ),DLOGNU(NFREQ)
      PARAMETER(NFRMIN=Nfreq/2)
      IntegerdLfrMax
      Common/observer/wH(Mfreq),cH(Mfreq),zerfr,Hcom(Mfreq),Hobs(Mfreq),freqob(Mfreq),dLfrMax
      Parameter(NP=15+15-1)
      Common/famu/fstatic(0:NP+1,Nfreq),fobs_corr(0:NP+1,Mfreq),fcom(0:NP+1,Mfreq),amustatic(0:NP+1)
      Common/rays/Pray(0:Np+1),fout(0:NP+1,Mfreq),abermu(0:NP+1),NmuNzon
      COMMON/LIM/Uplim,Haplim
      COMMON/AMM/DMIN,DM(Mzon),DMOUT,AMINI,AM(Mzon),AMOUT
      COMMON/Centr/RCE,Nzon
      Common/InEn/AMHT,EBurst,tBurst,tbeght
      COMMON/RADPUM/AMNI,XMNi,XNi,KmNick
      COMMON/RADGAM/FJgam(Mzon,2),toldg,tnewg
      COMMON/RADGlg/FJglog(Mzon,2)
      COMMON/CHEM/CHEM0(Mzon),RTphi(0:Mzon+1),EpsUq
      COMMON/REGIME/NREG(Mzon)
      doubleprecisionNRT
      COMMON/AQ/AQ,BQ,DRT,NRT
      COMMON/AZNUC/ACARB,ZCARB,ASI,ZSI,ANI,ZNI,QCSI,QSINI
      COMMON/QNRGYE/QNUC,RGASA,YELECT
      COMMON/CKN1/CK1,CK2,CFR,CRAP,CRAOLD
      LOGICALEVALJA,OLDJAC,BADSTE
      COMMON/EVAL/EVALJA,BADSTE,OLDJAC
      LogicalRadP
      COMMON/RadP/RadP
      COMMON/ARG/TP,PL,CHEM,LST,KENTR,JURS
      COMMON/RESULT/P,Egas,Sgas,ENG,CAPPA,PT,ET,ST,ENGT,CAPT,NZR
      COMMON/ABUND/XYZA,Yat(Natom)
      COMMON/AZ/AS,ZS,SCN
      COMMON/STR/PPL,EPL,SPL,ENGPL,CAPPL,CP,GAM,DA,DPE,DSE,DSP,BETgas
      COMMON/XELECT/XE,XET,XEPL,PE,Ycomp
      COMMON/URScap/Tpsqrt,Psicap,Scap,ScapT,ScapPl,ZMean,YZMean,ZMT,ZMPl,YZMT,YZMPl
      COMMON/BURNCC/CC,CCTP,CCPL,YDOT
      COMMON/ABarr/YABUN(Natom,Mzon)
      COMMON/UNSTL/UL,UPRESS,UE,UEPS,UCAP,UTIME,UV,UFLUX,UP
      COMMON/TAIL/KTAIL
      COMMON/UNINV/UPI,UEI
      COMMON/UNBSTL/UR,UM,UEPRI,ULGP,ULGE,ULGV,ULGTM,ULGEST,ULGFL,ULGCAP,ULGEPS
      Parameter(epsNi=3.9656224881D-02,epsCo=7.0232694190D-03,epspst=2.3346047930D-04,tNi=8.8000000000D+00,tCo=1.1130000000D+02)
      Parameter(Positr=3.21d-2)
      Parameter(gamfloor=-100d0)
      COMMON/ENUCOM/ENPLS,ENPAIR,ENPHO,ENURCA,ENDEP
      Common/Volanm/Ryzer,Kmcor
      Parameter(C8=0.5133979661305,Alp=2.784750039015)
      Parameter(ENINT=C8*alp/9.)
      Dataak/8./,Ivol/0/
      If(Ivol.EQ.0)then
      Kmcor=1
      Ivol=1
09999 IF(.NOT.(Am(Kmcor).LT.(ak-3.)/ak*Amout))GOTO09998
      Kmcor=Kmcor+1
      GOTO09999
09998 CONTINUE
      XNianm=8.*XMNi/(15.*Amout*Um*ENint)
      WRITE(4,*)' XNianm in Volen=',XNianm,'    Kmcor=',Kmcor
      endif
      IF(NREG(Kmarg).EQ.3)THEN
      If(KNadap.GT.0)then
      tday=T*UTIME/8.64D4
      ENGgam=XNi*(epsNi*EXP(-tday/tNi)+epsCo*(EXP(-tday/tCo)-EXP(-tday/tNi)))
      GammaJ=FJgam(Kmarg,2)
      if(tnewg.GT.toldg)GammaJ=GammaJ+(FJgam(Kmarg,2)-FJgam(Kmarg,1))*(t-tnewg)/(tnewg-toldg)
      ENG=ENGgam*GammaJ
      If(Kmarg.LE.KmNick)then
      Engpst=epspst*XNi*(EXP(-tday/tCo)-EXP(-tday/tNi))
      ENG=ENG+Engpst
      endif
      else
      tday=T*UTIME/8.64D4
      ENGgam=(epsNi*EXP(-tday/tNi)+epsCo*(EXP(-tday/tCo)-EXP(-tday/tNi)))
      GammaJ=FJgam(Kmarg,2)
      ENG=ENGgam*GammaJ
      Engpst=epspst*XNifor(Kmarg)*(EXP(-tday/tCo)-EXP(-tday/tNi))
      ENG=ENG+Engpst
      endif
      IF((AM(Kmarg)-AMini)*UM.LE.AMHT.AND.t*Utime.GT.tbeght.AND.t*Utime.LE.tburst+tbeght)THEN
      Eng=Eng+Eburst*1.D+38/(AMHT*CMS*tburst)
      ELSEIF(Kmarg.GT.1)then
      if((AM(Kmarg)-AMini)*UM.GT.AMHT.AND.(AM(Kmarg-1)-AMini)*UM.LT.AMHT.AND.t*Utime.LE.tburst)THEN
      Eng=Eng+Eburst*1.D+38/(AMHT*CMS*tburst)*(AMHT-(AM(Kmarg-1)-AMini)*UM)/(Dm(Kmarg)*UM)
      endif
      ENDIF
      ENDIF
      ENGT=0.D0
      ENGPL=0.D0
      RETURN
      END
