#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}



function error {
	echo
	more diff.txt
	echo
	echo "******* failed ******** diff final_check.mod" "$1"
	echo
}


# function do_one {
#   echo $1
#   cd $1  
#   svn del mesa_dir.rb mesh.rb mesh_plan.rb mesh_plot_data plot_data plotters
#   cd ..
# }


function do_one_svn {
  echo $1
  cd $1
  
  # do rm out.txt before running this
  
  svn diff -r 13119 inlist_* >> ../out.txt
  cd ..
}

function do_onex {
cd $1
if [ -z profile_columns.list ]
then
  pwd
  cp ../../defaults/profile_columns.list profile_columns.list
  svn add profile_columns.list
fi
if [ -z history_columns.list ]
then
  pwd
  cp ../../defaults/history_columns.list history_columns.list
  svn add history_columns.list
fi
cd ..
}

function do_onexx {
cd $1
if [ -z $3 ]
then
  echo
elif [ "$3" == skip ]
then
  echo
else
  pwd
  cp "$3" /Users/bpaxton/mesa/star/test_suite/$1/final_check.mod
fi
cd ..
}

function do_onex {
cd $1
if [ ! -r final_check.mod ]
then
  if [ ! -z $3 ]
  then
    pwd
    echo cp $3 final_check.mod
    cp $3 final_check.mod
    #svn add final_check.mod
  elif [ -r final.mod ]
  then
    pwd
    echo cp final.mod final_check.mod
    cp final.mod final_check.mod
    #svn add final_check.mod
  fi
fi
cd ..
}

function do_one {
    cd $1
    if ! grep 'test_suite_helpers' rn > /dev/null; then
        echo $1
    fi
    cd ..
}


date
source do1_test_source
echo ""
date
