#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"


if [ -z "$MESA_RUN_OPTIONAL" ]; then
    cp standard_30M_mesa_201_lgT9p78.mod 30M_mesa_201_lgT9p78.mod
else
   do_one inlist_initial_header standard_30M_mesa_201_lgT9p78.mod
   cp 30M_mesa_201_lgT9p78.mod standard_30M_mesa_201_lgT9p78.mod
fi

do_one inlist_30M_big_net_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


