#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


echo 'create ionization_data'

rm -rf ionization_data

echo 'tar xfJ ionization_data.tar.xz'
tar xfJ test/ionization_data.tar.xz
check_okay

rm -rf ../data/ionization_data
check_okay

mkdir ../data/ionization_data
check_okay

mv ionization_data/*.data ../data/ionization_data
check_okay

mkdir ../data/ionization_data/cache
check_okay

echo "done"
