include ../../../make/defaults-module.mk

# Build

MODULE_NAME := adipls
SRCS := adipls.c.d.f \
        adirhs.c.d.f \
        anldet.d.f \
        cmparr.d.f \
        danorm.d.f \
        decicd.d.f \
        delta1.d.f \
        delta2.d.f \
        delta3.d.f \
        dmpgsm.d.f \
        dmpmde.d.f \
        dmpsum.d.f \
        dump_obs.c.d.f \
        geninh.d.f \
        gm1ker.n.d.f \
        gravpo.n.d.f \
        kiner.n.d.f \
        mchcff.d.f \
        mchsol.n.d.f \
        nrkint.c.d.f \
        nrkm.d.f \
        nrtssl.d.f \
        order.d.f \
        rdfrqr.d.f \
        readml.n.d.f \
        readsm.d.f \
        res_adimod.c.d.f \
        res_adipar.c.d.f \
        rotker.c.d.f \
        rsnfit.n.d.f \
        sclasl.c.d.f \
        setbcs.n.d.f \
        setobs_st.c.d.f \
        set_rotation.c.d.f \
        setssm.n.d.f \
        setsum.d.f \
        setups_adi.c.d.f \
        shtint.c.d.f \
        sigint.n.d.f \
        sigitc.c.d.f \
        sigitr.n.d.f \
        signew.n.d.f \
        sigout.c.d.f \
        sigscn.c.d.f \
        sigsol.c.d.f \
        sph.d.f \
        stevft.n.d.f \
        sumout.d.f \
        takata.d.f \
        trnmod.n.d.f \
        uhx.d.f \
        user_adi.c.d.f \
        varfrq.n.d.f \
        xlmult.d.f

SRCS_CHECK :=
INTERNAL_DEPENDS_ON := const
EXTERNAL_DEPENDS_ON :=
BINTYPE = static-lib
INCLUDE_DIRS := -I.

CHECK_RESULTS_GOLDEN :=

include $(MAKE_DIR)/Makefile
