#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_start_header start.mod
cp start.mod standard_start.mod

do_one inlist_to_end_core_h_burn_header end_core_h_burn.mod
cp end_core_h_burn.mod standard_end_core_h_burn.mod

do_one inlist_to_start_he_core_flash_header start_he_core_flash.mod
cp start_he_core_flash.mod standard_start_he_core_flash.mod

do_one inlist_to_end_core_he_burn_header end_core_he_burn.mod
cp end_core_he_burn.mod standard_end_core_he_burn.mod

do_one inlist_to_agb_header agb.mod
cp agb.mod standard_agb.mod

do_one inlist_to_pulse_header pulse.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

