#!/usr/bin/env bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

./touch

echo "removing some data to force reinstall"
rm -rf data/atm_data
rm -rf data/eosDT_data
rm -rf data/kap_data
rm -rf data/ionization_data
rm -rf data/chem_data
rm -rf data/colors_data/filters data/colors_data/stellar_models data/colors_data/.extraction_complete
rm -rf data/rates_data/cache

rm -rf data/rates_data/cache/*

echo "finished clean"
echo
