#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"


do_one inlist_make_late_pre_zams_header late_pre_zams.mod
cp late_pre_zams.mod standard_late_pre_zams.mod

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_end_core_he_burn_header after_core_he_burn.mod
cp after_core_he_burn.mod standard_after_core_he_burn.mod

do_one inlist_remove_envelope_header removed_envelope.mod
cp removed_envelope.mod standard_removed_envelope.mod

do_one inlist_to_end_core_c_burn_header after_core_c_burn.mod
cp after_core_c_burn.mod standard_after_core_c_burn.mod

do_one inlist_convert_header converted.mod
cp converted.mod standard_converted.mod

do_one inlist_part1_header part1.mod
cp part1.mod standard_part1.mod

do_one inlist_part2_header part2.mod
cp part2.mod standard_part2.mod

do_one inlist_part3_header part3.mod
cp part3.mod standard_part3.mod

do_one inlist_part4_header final.mod


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
echo 'finished'

