#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_make_late_pre_zams_header late_pre_zams.mod
do_one inlist_to_zams_header zams.mod
do_one inlist_to_end_core_he_burn_header after_core_he_burn.mod
do_one inlist_remove_envelope_header removed_envelope.mod
do_one inlist_to_end_core_c_burn_header after_core_c_burn.mod
do_one inlist_convert_header converted.mod
do_one inlist_finish_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
echo 'finished'

