#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_late_pre_zams.mod late_pre_zams.mod
else
   do_one inlist_make_late_pre_zams_header late_pre_zams.mod
   cp late_pre_zams.mod standard_late_pre_zams.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_zams.mod zams.mod
else
   do_one inlist_to_zams_header zams.mod
   cp zams.mod standard_zams.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_after_core_he_burn.mod after_core_he_burn.mod
else
   do_one inlist_to_end_core_he_burn_header after_core_he_burn.mod
   cp after_core_he_burn.mod standard_after_core_he_burn.mod
fi

do_one inlist_remove_envelope_header removed_envelope.mod

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_after_core_c_burn.mod after_core_c_burn.mod
else
   do_one inlist_to_end_core_c_burn_header after_core_c_burn.mod
   cp after_core_c_burn.mod standard_after_core_c_burn.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_converted.mod converted.mod
else
   do_one inlist_convert_header converted.mod
   cp converted.mod standard_converted.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_part1.mod part1.mod
else
   do_one inlist_finish_part1_header part1.mod
   cp part1.mod standard_part1.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_part2.mod part2.mod
else
   do_one inlist_finish_part2_header part2.mod
   cp part2.mod standard_part2.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_part3.mod part3.mod
else
   do_one inlist_finish_part3_header part3.mod
   cp part3.mod standard_part3.mod
fi

do_one inlist_finish_part4_header final.mod


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
echo 'finished'

