#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_start.mod start.mod
else
   do_one inlist_start_header start.mod
   cp start.mod standard_start.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_pulse.mod pulse.mod
else
   do_one inlist_to_pulse_header pulse.mod
   cp pulse.mod standard_pulse.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_envelope.mod envelope.mod
else
   do_one inlist_remesh_header envelope.mod
   cp envelope.mod standard_envelope.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_initialized.mod initialized.mod
else
   do_one inlist_initialize_header initialized.mod
   cp initialized.mod standard_initialized.mod
fi

do_one inlist_RSG_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

