#!/bin/bash

# uncomment the following line to skip the optional inlists
# MESA_SKIP_OPTIONAL=t

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

# set MESA_SKIP_OPTIONAL to run all parts of test
if [ -n "$MESA_SKIP_OPTIONAL" ]; then
    do_one inlist_pre_ms_header 2M_pre_ms.mod LOGS_pre_ms
    do_one inlist_to_TACHeB_header 2M_TACHeB.mod LOGS_TACHeB
    do_one inlist_to_3DUP_header 2M_3DUP.mod LOGS_3DUP
    cp 2M_3DUP.mod standard_2M_3DUP.mod
else
    echo "Skipping pre_ms -> 3DUP evolution using saved model"
    cp standard_2M_3DUP.mod 2M_3DUP.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
    do_one inlist_to_lgL_3.79_header lgL_3.79.mod LOGS_to_lgL_3.79
    cp lgL_3.79.mod standard_lgL_3.79.mod
else
    echo "Skipping 3DUP evolution to lgL=3.79 using saved model"
    cp standard_lgL_3.79.mod lgL_3.79.mod
fi

do_one inlist_c13_pocket_header final.mod LOGS_c13_pocket

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for c13_pocket'
