#!/usr/bin/env bash

set -e

# uncomment the following line to skip the optional inlists
# MESA_SKIP_OPTIONAL=t

run_model() {
   local inlist_name="$1"
   local output_model="$2"

   rm -f restart_photo "$output_model"
   MESA_INLIST="$inlist_name" make run

   if [ ! -r "$output_model" ]; then
      echo "failed to create $output_model when running $inlist_name"
      exit 1
   fi
}

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

# check if can skip building starting model
if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_he_dep.mod he_dep.mod
else
   run_model inlist_to_he_dep_header he_dep.mod
   cp he_dep.mod standard_he_dep.mod
fi

run_model inlist_pulses_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'
