#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

#if [ -z "$MESA_RUN_OPTIONAL" ]; then
#   cp standard_late_pre_zams.mod late_pre_zams.mod
#else
   #do_one inlist_make_late_pre_zams_header late_pre_zams.mod LOGS_to_late_pre_zams
   #fi

#if [ -z "$MESA_RUN_OPTIONAL" ]; then
#   cp standard_start_core_collapse.mod start_core_collapse.mod
#else
   do_one inlist_to_start_core_collapse_header start_core_collapse.mod LOGS_to_start_core_collapse
   #fi

#do_one inlist_finish_core_collapse_header final.mod LOGS_to_finish

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

