#!/usr/bin/env bash

#echo $#
#echo $1
#echo $2

photo_directory=photos

function most_recent_photo {
    ls -t "$photo_directory" | head -1
}

if [ "$#" -ne 2 ]
then
    echo "must pass two arguments, photo string and inlist name"
    exit 1
fi

if [ $1 = "." ]
then
    photo=$(most_recent_photo)
else
    photo=$1
fi

if [ -z "$photo" ] || ! [ -f "$photo_directory/$photo" ]
then
    echo "specified photo does not exist"
    exit 1
fi

echo "restart from $photo"
if ! cp "$photo_directory/$photo" restart_photo
then
    echo "failed to copy photo"
    exit 1
fi

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
./star $2
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
