#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
	   echo FAILED
		exit 1
	fi
}

echo 'create eosSCVH_PT_data'
rm -rf eosSCVH_PT_data
check_okay

echo 'tar -xJf eosSCVH_PT_data.tar.xz'
tar -xJf eosSCVH_PT_data.tar.xz
check_okay

mkdir -p ../data/eosSCVH_PT_data
check_okay

mv eosSCVH_PT_data/*.data ../data/eosSCVH_PT_data
check_okay
