#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
	   echo FAILED
		exit 1
	fi
}

echo 'create eosPT_data'
rm -rf eosPT_data
check_okay

echo 'tar -xJf eosPT_data.tar.xz'
tar -xJf eosPT_data.tar.xz
check_okay

#tar -xJvf ../eosPT_SCVH_data.tar.xz
#check_okay

mkdir -p ../data/eosPT_data
check_okay

mv eosPT_data/*.data ../data/eosPT_data
check_okay

#mv data/eosPT_SCVH_data/*.data ../data/eosPT_data
#check_okay

mkdir -p ../data/eosPT_data/cache
check_okay
