#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 6310   L 57
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
    6576       1          0.1574E-04          63518.9206              0.7352             65.8743              0.0112             89.6039
    6576       2          0.2142E-04          46675.7891              0.5402             24.9131              0.0217             46.1159

after remove core  2d6  Teff 6310  L 57
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1       1          0.1575E-04          63510.0422              0.7351             65.7710              0.0112             89.4759
       1       2          0.2143E-04          46657.1417              0.5400             24.8922              0.0217             46.0955

after remesh            Teff 6308  L 57
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1       1          0.1568E-04          63780.6739              0.7382             53.7419              0.0137             72.8010
       1       2          0.2126E-04          47042.0297              0.5445             19.8127              0.0275             36.3890

after initialize        Teff 6308   L 57
   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1          0.1568E-04          63780.6739              0.7382              0.0137             72.8010
       2          0.2126E-04          47042.0297              0.5445              0.0275             36.3890
       3          0.2764E-04          36178.5958              0.4187              stable
 set gyre starting velocities for order 1
