#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod
do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod
do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod
do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod
do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod
do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod
do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

return

after to_pulse
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     360       1          0.3557E-04          28115.3143              0.3254            424.9207
     360       2          0.4248E-04          23537.9135              0.2724             23.9988
after remove core
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     100       1          0.3676E-04          27206.6828              0.3149            221.7376
     100       2          0.4315E-04          23172.5213              0.2682             22.8887
after remesh
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     100       1          0.3657E-04          27345.5098              0.3165             88.4196
     100       2          0.4189E-04          23871.6838              0.2763             13.7597
