ROOT = ../..
include $(ROOT)/../../utils/makefile_header

FFLAGS = -w

OFILES =\
inrnge.o intmdl.d.o rdamdl.n.d.o rdfreq.d.o rdfrqe.d.o rdfrqm.d.o \
rseta4.c.d.o setssm.d.o srdist.c.d.o wrfreq.d.o

default: ofiles

ofiles: $(OFILES)

clean:
	-@rm -f *.o
