#!/bin/bash

# Declare the arrays you want to loop over 
declare -a winds=('0.2' '0.5' '1.0') #'3.6' '3.8') #'3.2' '3.4' '2.6' '2.8' '3.0') 
declare -a masses=('18') 
declare -a meshdeltas=('1') #'1' '5d-1' '25d-2' '1d-2') 
declare -a timedeltas=('1') #'1' '5d-1' '25d-2' '1d-2') 

# Set up outputs
export OUTDIR=NEWERTESTING # set your output directory -- you could also hard-code a path, e.g. '/home/jgoldberg/Projects/path/to/output/directory/'
mkdir $OUTDIR # If it doesn't exist, make it
mkdir $OUTDIR'/BACKUPS/' # Also make a backup directory... 

# Run all the models! 
for ((h=0;h<${#masses[@]};++h)) # For mass in masses
	do 
		export mass=${masses[h]} 
		echo $mass
		for ((i=0;i<${#winds[@]};++i)) # For wind in winds
			do
				export wind=${winds[i]}
				echo $wind
				for ((j=0;j<${#meshdeltas[@]};++j)) # For mesh in meshdeltas 
					do
						export meshdelta=${meshdeltas[j]} 
						echo $meshdelta
						for ((k=0;k<${#meshdeltas[@]};++k)) # For time in timedeltas
							do
								export timedelta=${timedeltas[k]} 
								echo $timedelta

								# Copy your template inlists with filler words to the actual inlists
								# cp inlist_project_temp inlist_project # Commented out because I didn't want to do resolution testing with this right now 
								cp inlist_extra_temp inlist_extra

								# Now replace the filler words with mass, wind, time delta, mesh delta --

								# Edit inlist_extra to run with new mass and wind
								sed -i'' -e 's/initmass/'$mass'/g' inlist_extra
								sed -i'' -e 's/brottwindscale/'$wind'/g' inlist_extra

								# Edit inlist_project to use new resolution
								sed -i'' -e 's/timedeltascale/'$timedelta'/g' inlist_project
								sed -i'' -e 's/meshdeltascale/'$meshdelta'/g' inlist_project
								
								# Run the code! 
								echo "RUNNING" 
								./rn
								# mkdir LOGS # For debugging only
								
								# now, move the LOGS!
								# Create name of LOGS directory
								export LOGDIR='LOGS_mass_'$mass'_wind_'$wind'_mesh_'$meshdelta'_time_'$timedelta

								echo $LOGDIR

								# Make a copy of the inlists and put it in the LOGS, so you always can know what inlists you used
								mkdir LOGS/inlists/
								cp inlist_extra LOGS/inlists
								cp inlist_project LOGS/inlists
								
								
								# What to do if the OUTDIR/LOGDIR already exists? 
								mv $OUTDIR'/'$LOGDIR $OUTDIR'/BACKUPS/'$LOGDIR'_backup' # If the output directory already exists, move it to backup 
								rm -r $OUTDIR/$LOGDIR # Delete the directory so we know the new one is clean
								
								# Move your LOGS to the proper output spot
								mv LOGS $OUTDIR'/'$LOGDIR 

						done # time loop
				done # mesh loop
		done # wind loop
done # mass loop


echo "Finished directories" # Yay, we're done with all 4!


### Scratch notes: 

### Equivalent ish but with different syntax, useful expressions: 
# for value in "${arr[@]}"
# 	do
### Is equivalent to 
# for ((i=0;i<${#arr[@]};++i)) # For wind in winds
# 	do  
#      export value=${arr[i]} 

