#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 2980   L 3682
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
   12990       1          0.5077E-07       19695057.3370            227.9521           1683.0491              0.1354              7.3833
   12990       2          0.1007E-06        9933423.3090            114.9702            926.5560              0.1241              8.0591

after remove core       
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.5077E-07       19694731.7498            227.9483           1683.0153              0.1354              7.3833
       1       2          0.1007E-06        9933267.8102            114.9684            926.5437              0.1241              8.0591

after remesh            
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.5172E-07       19333153.7254            223.7634           2099.1460              0.1066              9.3811
       1       2          0.1030E-06        9708823.0538            112.3706           1270.8995              0.0884             11.3099

after initialize        
   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1          0.5172E-07       19333153.7254            223.7634              0.1066              9.3811
       2          0.1030E-06        9708823.0538            112.3706              0.0884             11.3099
       3          0.1624E-06        6156274.9723             71.2532              0.0734             13.6240
 set gyre starting velocities for order 1
