#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}
mkdir -p data/eosPT_data
echo ""
echo "Doing Z=0.00"
echo ""
echo 0.00 > whichz.txt
./ceos
check_okay

echo 'only doing Z=0.0 for scvh'
exit

echo "Doing Z=0.02"
echo ""
echo 0.02 > whichz.txt
./ceos
check_okay
echo "Doing Z=0.04"
echo ""
echo 0.04 > whichz.txt
./ceos
check_okay


echo "**************"
echo "**************"
echo "next step is"
echo "./build_eosPT_4_export"
echo "or"
echo "./build_eosPT_SCVH_4_export"
echo "**************"
echo "**************"
