#!/bin/bash

function check_okay {
    if [ $? -ne 0 ]
    then
        echo "Error in colors data build process"
        exit 1
    fi
}

# Create necessary directories
mkdir -p data
check_okay
cd data
check_okay
