#!/bin/bash

set -e  # Immediately exit on error

function check_okay {
    if [ $? -ne 0 ]; then
        echo "Error in colors data build process"
        exit 1
    fi
}

# Create working directory
mkdir -p ../data/colors_data
cd ../data/colors_data

# Variables
ARCHIVE_NAME="colors_data.txz"
EXTRACTED_FLAG=".extraction_complete"
TARGET_DIR="../data/colors_data"

# Validate archive
validate_archive() {
    tar -tJf "$ARCHIVE_NAME" > /dev/null 2>&1
}

# If not extracted yet
if [ ! -f "$EXTRACTED_FLAG" ]; then

    # If the archive is missing
    if [ ! -f "$ARCHIVE_NAME" ]; then
        echo "Archive $ARCHIVE_NAME is missing."
        echo "Please ensure $ARCHIVE_NAME is downloaded or available in this directory."
        # it should now auto-download from a LFS pointer... i think?
        git -C "$MESA_DIR" lfs pull --include="data/colors_data/colors_data.txz"   #like this
        
        if [ ! -f "$ARCHIVE_NAME" ]; then
            echo "Archive $ARCHIVE_NAME is still missing."
            exit 1
        fi
    fi

    # Validate it
    if ! validate_archive; then
        echo "Archive $ARCHIVE_NAME is invalid."
        git -C "$MESA_DIR" lfs pull --include="data/colors_data/colors_data.txz"   #and again...

        # Validate it
        if ! validate_archive; then
            echo "Archive $ARCHIVE_NAME is invalid."
            exit 1
        fi
    fi

    echo "Extracting colors data..."
    mkdir -p filters stellar_models
    tar -xJf "$ARCHIVE_NAME"
    touch "$EXTRACTED_FLAG"
    # rm "$ARCHIVE_NAME"

else
    echo "Colors data already extracted."
fi


cd ..


for SUBDIR in filters stellar_models; do
    if [ -d "data/$SUBDIR" ]; then
        check_okay
    fi
done

echo "Colors data has been successfully built and exported."
