#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one ../pre_ms_shared_inlists/inlist_make_late_pre_zams_header late_pre_zams.mod
cp late_pre_zams.mod standard_late_pre_zams.mod

do_one ../pre_ms_shared_inlists/inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one ../pre_ms_shared_inlists/inlist_to_end_core_he_burn_header after_core_he_burn.mod
cp after_core_he_burn.mod standard_after_core_he_burn.mod

do_one ../pre_ms_shared_inlists/inlist_remove_envelope_header removed_envelope.mod
cp removed_envelope.mod standard_removed_envelope.mod

do_one ../pre_ms_shared_inlists/inlist_to_end_core_c_burn_header after_core_c_burn.mod
cp after_core_c_burn.mod standard_after_core_c_burn.mod
   
do_one inlist_to_start_infall_header start_infall.mod
cp start_infall.mod standard_start_infall.mod

do_one ../pre_ms_shared_inlists/inlist_convert_header converted.mod
cp converted.mod standard_converted.mod

do_one ../pre_ms_shared_inlists/inlist_finish_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

