#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 4892   L 4659
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
     740       1          0.6490E-06        1540869.3168             17.8341              0.0385             25.9494
     740       2          0.9823E-06        1018064.9306             11.7832              0.0331             30.1896

after remove core  5d6  Teff 4892   L 4659
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1       1          0.6490E-06        1540852.4354             17.8339              0.0385             25.9478
       1       2          0.9823E-06        1018033.7929             11.7828              0.0331             30.1903

after remesh            Teff 4891   L 4658    with dt = 1 sec for 1 step.   RSP2_use_L_eqn_at_surface = .false.
   model   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1       1          0.6309E-06        1585060.9856             18.3456              0.0580             17.2547
       1       2          0.9567E-06        1045300.1455             12.0984              0.0394             25.3910

after initialize        Teff 4892   L 4660
 set gyre starting velocities
   order           freq (Hz)             P (sec)             P (day)    cycles to double
       1          0.6309E-06        1585057.8321             18.3456             17.2548
       2          0.9567E-06        1045298.0074             12.0984             25.3906
       3          0.1399E-05         714569.8871              8.2705              stable
