include ../../make/defaults-module.mk

MODULE_NAME := free-eos-builder
SRCS := src/free_eos_table.f90
INTERNAL_DEPENDS_ON := const utils math chem eos
EXTERNAL_DEPENDS_ON := free-eos
INCLUDE_DIRS :=
BINTYPE := executable

include ../../make/Makefile
