#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

echo 'create kap_data'

mkdir -p data
cd data
check_okay

rm -rf kap_data

echo 'tar xfJ kap_data.tar.xz'
tar xfJ ../kap_data.tar.xz
check_okay

echo 'tar xfJ kapcn_data.txz'
tar xfJ ../kapcn_data.txz
check_okay

echo 'copy AESOPUS_AGSS09.h5'
cp ../AESOPUS_AGSS09.h5 kap_data
check_okay

cd ..

rm -rf ../data/kap_data
check_okay

mkdir ../data/kap_data
check_okay

mv data/kap_data/*.data ../data/kap_data
check_okay

mv data/kap_data/*.h5 ../data/kap_data
check_okay

mkdir ../data/kap_data/cache
check_okay
