      DOUBLEPRECISIONFUNCTIONDMACH(JOB)
      INTEGERJOB
      DOUBLEPRECISIONEPS,TINY,HUGE,S
      EPS=1.0D0
10    EPS=EPS/2.0D0
      S=1.0D0+EPS
      IF(S.GT.1.0D0)GOTO10
      EPS=2.0D0*EPS
      S=1.0D0
      HUGE=1.0D0/TINY(0.d0)
      IF(JOB.EQ.1)DMACH=EPS
      IF(JOB.EQ.2)DMACH=TINY(0.d0)
      IF(JOB.EQ.2)then
      ENDIF
      IF(JOB.EQ.3)DMACH=HUGE
      RETURN
      END
