      subroutineedensol(rho,T,abundx,eden,maxiter,acc,numelems)
      implicitreal*8(a-h,o-z)
      PARAMETER(MAXIONM1=(6-1))
      PARAMETER(NSBINTVL=3*10)
      parameter(inucmas=99)
      real*8nucmass(inucmas)
      real*8abundx(99),rho,eden,T
      integerindexv(99)
      integernumelems
      real*8frac(0:6),partition(0:6)
      saveptrnucmass,init
      datainit/1/
      datapi/3.141592653589793d+00/,fourpi/12.5637061d+00/
      databc/1.380626d-16/,h/6.626205d-27/,hev/4.1357d-15/
      datac/2.997925d+10/,elecxsec/6.6524d-25/
      dataevtoerg/1.6022d-12/,a/7.56464d-15/
      datastefbltz/5.66956d-05/,hmass/1.67352d-24/
      dataesu/4.80298d-10/,emass/9.1091d-28/
      datasrpi/1.772453851d+00/,bcev/8.617064d-05/
      if(init.eq.1)then
      callsetnucms(nucmass)
      init=0
      eden=0.d0
      endif
      delta=1.d-05
      deltap1=1.d+00+delta
      calltablsort(99,abundx,indexv,-1)
      dennuc=0.d+00
      doizmax=1,numelems
      dennuc=dennuc+rho*abundx(indexv(izmax))/nucmass(indexv(izmax))
      enddo
      if(eden.lt.1.d-05)eden=dennuc
      Templog=dlog(T)
      hckT=h*c/(bc*T)
      doiter=1,maxiter
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      	eden=max(eden*dexp(min(dlned,2.3025851d0)),0.1d0*eden)
      if(dabs(dlned).lt.acc)return
      enddo
      NITMAX=maxiter
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      IFAIL=1
      ian=0
      ITQ=0
      IF(.NOT.(dlned.LT.0.))GOTO09999
09996 IF(.NOT.((dlned.LT.0..AND.ITQ.lt.NITMAX)))GOTO09995
      Ast=10.**(min(-12+ian,-1))*eden
      eden=eden-Ast
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      ian=ian+1
      ITQ=ITQ+1
      GOTO09996
09995 CONTINUE
      GOTO09997
09999 CONTINUE
      IF(.NOT.(dlned.GT.0.))GOTO09998
09993 IF(.NOT.((dlned.GT.0..AND.ITQ.lt.NITMAX)))GOTO09992
      Ast=10.**(min(-12+ian,-1))*eden
      eden=eden+Ast
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      ian=ian+1
      ITQ=ITQ+1
      GOTO09993
09992 CONTINUE
      GOTO09997
09998 CONTINUE
      IFAIL=0
09997 CONTINUE
      Errest=abs(dlned)
09990 IF(.NOT.((abs(Ast).GT.acc*abs(eden).OR.(ITQ.GT.2.AND.abs(dlned).LT.Errest).AND.(ITQ.LT.NITMAX)).AND.IFAIL.NE.0))GOTO09989
      Errest=abs(dlned)
      Ast=+0.5D0*SIGN(Ast,dlned)
      eden=eden+Ast
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      ITQ=ITQ+1
      GOTO09990
09989 CONTINUE
      If(abs(dlned).GE.ERREST)then
      eden=eden-Ast
      press=bc*T*(eden+dennuc)
      edz=0.d+00
      dedzded=0.d+00
      doizmax=1,numelems
      iz=indexv(izmax)
      if(abundx(iz).gt.0.d+00)then
      ionmax=min(iz+1,6)
      ionmaxm1=ionmax-1
      dentot=rho*abundx(iz)/nucmass(iz)
      callsahaeqn(1,.true.,press,T,eden,iz,6,i1,frac,partition)
      doi=1,ionmax
      edz=edz+frac(i)*dentot*dble(i+i1-2)
      enddo
      dpress=bc*T*eden*delta
      callsahaeqn(1,.true.,press+dpress,T,eden*deltap1,iz,6,i1,frac,partition)
      doi=1,ionmax
      dedzded=dedzded+frac(i)*dentot*dble(i+i1-2)
      enddo
      endif
      enddo
      dedzded=(dedzded-edz)/(delta*eden)
      chrgxs=edz-eden
      dchrdlne=eden*dedzded-eden
      dlned=-chrgxs/dchrdlne
      IFAIL=0
      Endif
      If(abs(Ast).LE.acc*abs(eden))IFAIL=0
      IF(IFAIL.NE.0)then
      WRITE(*,*)' stop in edensol.trf IFAIL=',IFAIL
      STOP320
      endif
      IF(IFAIL.ne.0)then
      write(0,*)' * Failure to obtain convergence of electron',' density in EDENSOL. ** '
      write(0,1010)rho,T,eden,acc,maxiter
1010  format(' * rho: ',1pe12.5,' T:  ',1pe12.5,/,' ** eden:  ',1pe12.5,' acc:',1pe12.5,/,' ** maxiter: ',i5,/,' <z,  abund> ')
1020  format(i4,1x,1pe12.5)
      write(0,1020)(iz,abundx(iz),iz=1,99)
      write(0,*)'-----------------------------','-----------------------------'
      ENDIF
      return
      end
