#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

return

after to_pulse       Teff 2676   logL 3.72    near peak of He shell flash
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
    1985       1          0.2706E-07       36954653.6617            427.7159              1.8403
    1985       2          0.6113E-07       16359513.7145            189.3462              2.3921
after remove core    Teff 2676   logL 3.72
     100       1          0.2706E-07       36951672.5334            427.6814              1.8401
     100       2          0.6114E-07       16356779.3298            189.3146              2.3916
after remesh         Teff 2677   logL 3.72 (at step 1)
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
      10       1          0.2687E-07       37213959.9325            430.7171              1.5140
      10       2          0.6040E-07       16556936.1610            191.6312              2.0905
after initialize
 set gyre starting velocities
   order           freq (Hz)             P (sec)             P (day)    cycles to double
       1          0.2687E-07       37213959.9325            430.7171              1.5140
       2          0.6040E-07       16556936.1610            191.6312              2.0905
