#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

return

after to_pulse
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     610       1          0.1688E-07       59236127.2640            685.6033             10.8349
     610       2          0.4138E-07       24165261.1913            279.6905             11.7369
after remove core
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     100       1          0.1675E-07       59718754.5326            691.1893             10.7372
     100       2          0.4116E-07       24294067.3288            281.1813             11.7150
after remesh
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     100       1          0.1686E-07       59297596.0123            686.3148              9.5035
     100       2          0.4147E-07       24115264.4040            279.1119             12.1100
