#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_zams.mod zams.mod
else
   do_one inlist_to_zams_header zams.mod
   cp zams.mod standard_zams.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_near_pulses.mod near_pulses.mod
else
   do_one inlist_to_near_pulses_header near_pulses.mod
   cp near_pulses.mod standard_near_pulses.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_near_pulses2.mod near_pulses2.mod
else
   do_one inlist_to_near_pulses2_header near_pulses2.mod
   cp near_pulses2.mod standard_near_pulses2.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_pulse.mod pulse.mod
else
   do_one inlist_to_pulse_header pulse.mod
   cp pulse.mod standard_pulse.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_converted.mod converted.mod
else
   do_one inlist_convert_header converted.mod
   cp converted.mod standard_converted.mod
fi

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_initialized.mod initialized.mod
else
   do_one inlist_initialize_header initialized.mod
   cp initialized.mod standard_initialized.mod
fi

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

