! ***********************************************************************
!
!   Copyright (C) 2010  Bill Paxton
!
!   MESA is free software; you can use it and/or modify
!   it under the combined terms and restrictions of the MESA MANIFESTO
!   and the GNU General Library Public License as published
!   by the Free Software Foundation; either version 2 of the License,
!   or (at your option) any later version.
!
!   You should have received a copy of the MESA MANIFESTO along with
!   this software; if not, it is available at the mesa website:
!   http://mesa.sourceforge.net/
!
!   MESA is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
!   See the GNU Library General Public License for more details.
!
!   You should have received a copy of the GNU Library General Public License
!   along with this software; if not, write to the Free Software
!   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
!
! ***********************************************************************

      program run

      use run_star_support, only: do_read_star_job
      use run_star, only: do_run_star
      use math_lib, only: math_backend
      use star_def
      
      implicit none
      
      integer :: ierr, iounit
      
      ierr = 0
      call do_read_star_job('inlist', ierr)
      if (ierr /= 0) stop 1
      
      call do_run_star

      ! write information for MESA TestHub
      open(newunit=iounit, file='../../testhub.yml')
      write(iounit,'(A)') '# This file is generated by star/test (see src/run.f90)'
      write(iounit,'(A)') '---'
      write(iounit,'(A)') 'compiler: ' // "'" // trim(compiler_name) // "'"
      write(iounit,'(A)') 'compiler_version: ' // "'" // trim(compiler_version_name) // "'"
      write(iounit,'(A)') 'sdk_version: ' // "'" // trim(mesasdk_version_name) // "'"
      write(iounit,'(A)') 'math_backend: ' // "'" // trim (math_backend) // "'"
      close(iounit)
      
      end program
