#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 2.26e4   L 7.05e4
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
     490       1          0.2069E-04          48343.5125              0.5595             50.0283              0.0112             89.4112
     490       2          0.2313E-04          43240.4905              0.5005            484.3540              0.0010            967.8009

after remove core  2d6  Teff 2.26e4   L 7.05e4
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.2151E-04          46498.0664              0.5382             31.7253              0.0170             58.9501
       1       2          0.2723E-04              0.0000              0.0000              stable

after remesh            Teff   L 
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double

after initialize        Teff 2.26e4   L 7.05e4
   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
 set gyre starting velocities for order 1
