#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 2.7e4   L 7.2e4
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
     364       1          0.3477E-04          28757.2557              0.3328            133.6411              0.0025            401.5191
     364       2          0.4145E-04          24126.8871              0.2792              6.9260              0.0403             24.8023

after remove core  2d6  Teff 2.7e4   L 7.2e4
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.3589E-04          27861.7463              0.3225             69.1884              0.0047            214.5551
       1       2          0.4209E-04          23760.1242              0.2750              6.5962              0.0417             23.9862

after remesh            Teff 2.7e4   L 7.2e4
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.3570E-04          28007.3344              0.3242             37.7780              0.0086            116.5415
       1       2          0.4099E-04          24396.2950              0.2824              5.3131              0.0531             18.8164

after initialize        Teff 2.7e4   L 7.2e4
   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1          0.3570E-04          28007.3344              0.3242              0.0086            116.5415
       2          0.4099E-04          24396.2950              0.2824              0.0531             18.8164
       3          0.5203E-04          19219.4414              0.2224              stable
 set gyre starting velocities for order 2
