#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_to_zams_header zams.mod
cp zams.mod standard_zams.mod

do_one inlist_to_near_pulses_header near_pulses.mod
cp near_pulses.mod standard_near_pulses.mod

do_one inlist_to_nearer_pulses_header nearer_pulses.mod
cp nearer_pulses.mod standard_nearer_pulses.mod

do_one inlist_to_pulse_header pulse.mod
cp pulse.mod standard_pulse.mod

do_one inlist_remove_core_header removed_core.mod
cp removed_core.mod standard_removed_core.mod

do_one inlist_remesh_header remeshed.mod
cp remeshed.mod standard_remeshed.mod

do_one inlist_initialize_header initialized.mod
cp initialized.mod standard_initialized.mod

do_one inlist_pulse_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


after to pulse          Teff 2.23e4   L 2957
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
     388       1          0.3123E-04          32018.8931              0.3706            145.4509              0.0025            392.4857
     388       2          0.3695E-04          27062.3151              0.3132            100.2962              0.0031            320.2089

after remove core 
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.3133E-04          31913.6949              0.3694            137.3380              0.0027            371.8154
       1       2          0.3707E-04          26973.1177              0.3122            112.6215              0.0028            360.7481

after remesh   
   model   order           freq (Hz)             P (sec)             P (day)        growth (day)              growth    cycles to double
       1       1          0.3115E-04          32105.7200              0.3716             96.3445              0.0039            259.2735
       1       2          0.3656E-04          27352.2085              0.3166             54.6816              0.0058            172.7279

after initialize        Teff    L 
   order           freq (Hz)             P (sec)             P (day)              growth    cycles to double
       1          0.3115E-04          32105.7200              0.3716              0.0039            259.2735
       2          0.3656E-04          27352.2085              0.3166              0.0058            172.7279
