#!/bin/bash

# uncomment the following line to run all parts of the test
# MESA_RUN_OPTIONAL=t

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_late_pre_zams.mod late_pre_zams.mod
else
   do_one inlist_make_late_pre_zams_header late_pre_zams.mod LOGS_to_late_pre_zams
   cp late_pre_zams.mod standard_late_pre_zams.mod
fi

# check if can skip
if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_after_core_he_burn.mod after_core_he_burn.mod
else
   do_one inlist_to_end_core_he_burn_header after_core_he_burn.mod
   cp after_core_he_burn.mod standard_after_core_he_burn.mod
fi

# check if can skip
if [ -z "$MESA_RUN_OPTIONAL" ]; then
   cp standard_lgT_9.5.mod lgT_9.5.mod
else
   do_one inlist_to_lgT_9.5_header lgT_9.5.mod
   cp lgT_9.5.mod standard_lgT_9.5.mod
fi

do_one inlist_to_cc_header start_core_collapse.mod

# check if can skip
#if [ -z "$MESA_RUN_OPTIONAL" ]; then
#   cp start_core_collapse.mod final.mod
#else
#   do_one inlist_finish_core_collapse_header final.mod
#fi

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

