#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_zams.mod zams.mod
else
   do_one inlist_to_zams_header zams.mod
   cp zams.mod standard_zams.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_near_pulses.mod near_pulses.mod
else
   do_one inlist_to_near_pulses_header near_pulses.mod
   cp near_pulses.mod standard_near_pulses.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_pulse.mod .mod
else
   do_one inlist_to_pulse_header pulse.mod
   cp pulse.mod standard_pulse.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_removed_core.mod removed_core.mod
else
   do_one inlist_remove_core_header removed_core.mod
   cp removed_core.mod standard_removed_core.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_remeshed.mod remeshed.mod
else
   do_one inlist_remesh_header remeshed.mod
   cp remeshed.mod standard_remeshed.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_initialized.mod initialized.mod
else
   do_one inlist_initialize_header initialized.mod
   cp initialized.mod standard_initialized.mod
fi

#do_one inlist_pulse_header final.mod 
do_one inlist_pulse_RSP2_header final.mod 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

return

after to_pulse
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     802       1          0.3849E-06        2598327.2651             30.0732             22.8442
     802       2          0.5887E-06        1698553.9560             19.6592             36.1827

after remove_core
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
     100       1          0.3824E-06        2614991.6486             30.2661             22.5777
     100       2          0.5856E-06        1707538.6565             19.7632             35.9831

after remesh
   model   order           freq (Hz)             P (sec)             P (day)    cycles to double
      10       1          0.3800E-06        2631867.1632             30.4614             13.3675
      10       2          0.5872E-06        1702893.5999             19.7094             27.2634

after initialized
   order           freq (Hz)             P (sec)             P (day)    cycles to double
       1          0.3800E-06        2631867.1633             30.4614             13.3675
       2          0.5872E-06        1702893.5999             19.7094             27.2634

