properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
])

def parallel_tests = 6;
def cores_per_test = 8;

buildPod(context: 'jenkins', cpus: parallel_tests*cores_per_test, memory: '128Gi') {
  withEnv([
    "MESA_DIR=$WORKSPACE",
    "HOME=$WORKSPACE",
    "NTESTS=$parallel_tests",
    "NPROCS=$cores_per_test", // this is only used by build?
    "OMP_NUM_THREADS=$cores_per_test" // this is used by tests?
  ]) {
    stage('setup') {
      withCredentials([
          usernamePassword(credentialsId: 'mesa_test', passwordVariable: 'MESA_TEST_PSW', usernameVariable: 'MESA_TEST_USR'),
          string(credentialsId: 'mesa_test_logs_token', variable: 'MESA_LOGS_TOKEN')]) {
        writeYaml(file: "$WORKSPACE/.mesa_test/config.yml", overwrite: true, data: [
          'computer_name': 'Jenkins',
          'email': env.MESA_TEST_USR,
          'password': env.MESA_TEST_PSW,
          'logs_token': env.MESA_LOGS_TOKEN,
          'github_protocol': ':ssh',
          'mesa_mirror': "$WORKSPACE/mirror", /* not used */
          'mesa_work': env.WORKSPACE,
          'platform': 'Linux',
          'platform_version': 'Ubuntu'
        ])
      }
      sh '''#!/bin/bash -ex
        source $MESASDK_ROOT/bin/mesasdk_init.sh
        mesa_test install --no-checkout
        mesa_test submit --empty
      '''
    }
    stage('tests') {
      sh '''#!/bin/bash
        source $MESASDK_ROOT/bin/mesasdk_init.sh
        ntests=0
        for f in $MESA_DIR/*/test_suite ; do
          nt=$(cd $f && ./count_tests)
          (( ntests+=nt ))
        done
        unset PARALLEL
        seq 1 $ntests | parallel -j$NTESTS --joblog test.log --timeout 86400 mesa_test test {} --force-logs
        r=$?
        cat test.log
        exit $r
      '''
    }
  }
}
