#!/bin/bash

# uncomment the following line to skip the optional inlists
# MESA_SKIP_OPTIONAL=t

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

# set MESA_SKIP_OPTIONAL to skip parts of test
if [ -z "$MESA_SKIP_OPTIONAL" ]; then
    do_one inlist_relax_mass_header wd_c_core_ignition.mod
fi

do_one inlist_wd_c_core_ignition_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for wd_c_core_ignition'
