      SUBROUTINEGdepos
      IMPLICITREAL*8(A-H,O-Z)
      PARAMETER(NVARS=3)
      include '../obj/nfreq_and_mzone.inc'
      PARAMETER(NYDIM=(NVARS+2*NFREQ)*Mzon,MAXDER=4)
      Parameter(Is=5)
      PARAMETER(NZ=3000000)
      Parameter(Nstage=28,Natom=15)
      PARAMETER(KOMAX=80)
      LogicalLSYSTEM
      Parameter(LSystem=.FALSE.)
      Parameter(Pi=3.1415926535897932d+00,hPlanc=1.0545716280D-27,Cs=2.9979245800D+10,Boltzk=1.3806504000D-16,Avogar=6.0221417900D+2
     *3,AMbrun=1.6605387832D-24,AMelec=9.1093821500D-28,echarg=4.8032042700D-10,CG=6.6742800000D-08,CMS=1.9884000000D+33,RSol=6.9551
     *000000D+10,ULGR=1.4000000000D+01,UPURS=1.0000000000D+07,ULGPU=7.0000000000D+00,ULGEU=1.3000000000D+01,UPC=3.0856776000D+18,UTP
     *=1.0000000000D+05,URHO=1.0000000000D-06,CARAD=7.5657680191D-15,CSIGM=5.6704004778D-05,ERGEV=1.6021764864D-12,GRADeV=1.16045052
     *85D+04,RADC=7.5657680191D-02,CTOMP=4.0062048575D-01,CCAPS=2.6901213726D+01,CCAPZ=9.8964034725D+00)
      IntegerZn(Natom),ZnCo(Natom+1)
      DimensionAZ(Natom)
      Common/AZZn/AZ,Zn,ZnCo
      Common/NiAdap/tday,t_eve,XNifor(Mzon),AMeveNi,KNadap
      LOGICALFRST
      Parameter(Mfreq=130)
      Common/Kmzon/km,kmhap,Jac,FRST
      COMMON/STCOM1/t,H,HMIN,HMAX,EPS,N,METH,KFLAG,JSTART
      COMMON/YMAX/YMAX(NYDIM)
      COMMON/YSTIF/Y(NYDIM,MAXDER+1)
      COMMON/HNUSED/HUSED,NQUSED,NFUN,NJAC,NITER,NFAIL
      COMMON/HNT/HNT(7)
      PARAMETER(DELTA=1.d-05)
      PARAMETER(LICN=4*NZ,LIRN=2*NZ)
      LogicalNEEDBR
      COMMON/STJAC/THRMAT,HL,AJAC(LICN),IRN(LIRN),ICN(LICN),WJAC(NYDIM),FSAVE(NYDIM*2),IKEEP(5*NYDIM),IW(8*NYDIM),IDISP(11),NZMOD,NE
     *EDBR
      LOGICALCONV,CHNCND,SCAT,SEP
      COMMON/CUTOFF/FLOOR(NVARS+1),Wacc(NVARS+1),FitTau,TauTol,Rvis,CONV,CHNCND,SCAT,SEP
      LogicalLTHICK
      COMMON/THICK/LTHICK(Nfreq,Mzon)
      COMMON/CONVEC/UC(Mzon),YAINV(Mzon)
      COMMON/RAD/EDDJ(Mzon,Nfreq),EDDH(Mzon),HEDD(Nfreq),HEDRAD,CLIGHT,CKRAD,UFREQ,CFLUX,CCL,CLUM,CLUMF,CIMP,NTHICK(NFREQ),NTHNEW(NF
     *REQ),bolM,NCND,KRAD,NFRUS
      LOGICALEDTM
      COMMON/RADOLD/HEDOLD,HINEDD,EDTM
      Common/newedd/EddN(Mzon,Nfreq),HEdN(Nfreq),tfeau
      Common/oldedd/EddO(Mzon,Nfreq),HEdo(Nfreq),trlx
      Common/cnlast/Cnlast
      Common/Dhap/DHaphR(Mzon,Nfreq)
      COMMON/BAND/FREQ(NFREQ+1),FREQMN(NFREQ),WEIGHT(130),HAPPAL(NFREQ),HAPABSRON(NFREQ),HAPABS(NFREQ),DLOGNU(NFREQ)
      PARAMETER(NFRMIN=Nfreq/2)
      IntegerdLfrMax
      Common/observer/wH(Mfreq),cH(Mfreq),zerfr,Hcom(Mfreq),Hobs(Mfreq),freqob(Mfreq),dLfrMax
      Parameter(NP=15+15-1)
      Common/famu/fstatic(0:NP+1,Nfreq),fobs_corr(0:NP+1,Mfreq),fcom(0:NP+1,Mfreq),amustatic(0:NP+1)
      Common/rays/Pray(0:Np+1),fout(0:NP+1,Mfreq),abermu(0:NP+1),NmuNzon
      COMMON/LIM/Uplim,Haplim
      COMMON/AMM/DMIN,DM(Mzon),DMOUT,AMINI,AM(Mzon),AMOUT
      COMMON/Centr/RCE,Nzon
      Common/InEn/AMHT,EBurst,tBurst,tbeght
      COMMON/RADPUM/AMNI,XMNi,XNi,KmNick
      COMMON/RADGAM/FJgam(Mzon,2),toldg,tnewg
      COMMON/RADGlg/FJglog(Mzon,2)
      COMMON/CHEM/CHEM0(Mzon),RTphi(0:Mzon+1),EpsUq
      COMMON/REGIME/NREG(Mzon)
      doubleprecisionNRT
      COMMON/AQ/AQ,BQ,DRT,NRT
      COMMON/AZNUC/ACARB,ZCARB,ASI,ZSI,ANI,ZNI,QCSI,QSINI
      COMMON/QNRGYE/QNUC,RGASA,YELECT
      COMMON/CKN1/CK1,CK2,CFR,CRAP,CRAOLD
      LOGICALEVALJA,OLDJAC,BADSTE
      COMMON/EVAL/EVALJA,BADSTE,OLDJAC
      LogicalRadP
      COMMON/RadP/RadP
      COMMON/ARG/TP,PL,CHEM,LST,KENTR,JURS
      COMMON/RESULT/P,Egas,Sgas,ENG,CAPPA,PT,ET,ST,ENGT,CAPT,NZR
      COMMON/ABUND/XYZA,Yat(Natom)
      COMMON/AZ/AS,ZS,SCN
      COMMON/STR/PPL,EPL,SPL,ENGPL,CAPPL,CP,GAM,DA,DPE,DSE,DSP,BETgas
      COMMON/XELECT/XE,XET,XEPL,PE,Ycomp
      COMMON/URScap/Tpsqrt,Psicap,Scap,ScapT,ScapPl,ZMean,YZMean,ZMT,ZMPl,YZMT,YZMPl
      COMMON/BURNCC/CC,CCTP,CCPL,YDOT
      COMMON/ABarr/YABUN(Natom,Mzon)
      COMMON/UNSTL/UL,UPRESS,UE,UEPS,UCAP,UTIME,UV,UFLUX,UP
      COMMON/TAIL/KTAIL
      COMMON/UNINV/UPI,UEI
      COMMON/UNBSTL/UR,UM,UEPRI,ULGP,ULGE,ULGV,ULGTM,ULGEST,ULGFL,ULGCAP,ULGEPS
      Parameter(tret=1.d0/3.d0)
      Parameter(Nfrgam=1)
      Parameter(shrink=0.9d0)
      Parameter(Capgam=5.d-02)
      COMMON/CONUR/EIT,DST,BBRCNR(5)
      COMMON/BAL/EL(MAXDER+1),YENTOT(MAXDER+1),ETOT0,ELVOL,ELSURF,ELTOT,TPSURF,HOLDBL,ELOST,EKO,RADBEG
      common/NSTEP/NSTEP,NDebug,MAXER,IOUT,NOUT
      common/CREAD/TAUOLD,NSTMAX,MBATCH,MAXORD
      common/debug/LfrDebug,Nperturb,Kbad
      REAL*8TPMAX(MAXDER+1),TQ(4)
      COMMON/TAU/TAU(Mzon+1),FLUX(Mzon)
      common/tauubvri/tauU(Mzon),tauB(Mzon),tauV(Mzon),tauR(Mzon),tauI(Mzon)
      COMMON/PHOT/XJPH,DMPH,RPH,TPH,PLPH,VPH,CHEMPH,GRVPH,HP,JPH
      PARAMETER(NFUNC=6)
      REAL*4WORK(Mzon+2,NFREQ),WRK(Mzon,4)
      REAL*8WRKX(Mzon),WORKX(Mzon+2)
      COMMON/STEPD/WRKX,WORKX,TPHOT,TEFF,WORK,WRK,NPHOT,NZM
      PARAMETER(TMCRIT=1.D-6,TPNSE=5.D0,EPGROW=0.02D0)
      Common/RUTP/Ry(Mzon),Uy(Mzon),Ty(Mzon),Press(Mzon),Rho(Mzon)
      COMMON/TOO/TOO,KO,KNTO,TO(KOMAX),STO(KOMAX),NTO(KOMAX)
      Parameter(Lcurdm=1000)
      RealTcurv
      IntegerNFRUSED
      REAL*8Flsave
      Common/Curve/tcurv(8,Lcurdm),Depos(Lcurdm),Flsave(MFREQ+1,Lcurdm),NFRUSED(Lcurdm),Lsaved
      LOGICALBEGRUN
      Common/BEGR/BEGRUN
      CHARACTER*80Model,Sumprf,Sumcur,Depfile,Flxfile
      COMMON/Files/Model,Sumprf,Sumcur,Depfile,Flxfile
      CHARACTER*1app
      LogicalGivdtl
      Common/ABGrap/NSTA,NSTB,TcurA,TcurB,Givdtl
      REAL*8MBOL,MU,MB,MV,MR,MI,MBOL1
      COMMON/COLOR/MBOL,MU,MB,MV,MR,MI,UMB,BMV,MBOL1,LubvU,LubvB,LubvV,LubvR,LubvI,Lyman
      COMMON/DETAIL/QRTarr(Mzon),UUarr(Mzon),ArrLum(Mzon),Acc(Mzon)
      Common/XYZ/XA,YA,URM
      Integersm_device
      Character*40chalab
      DimensionRMPray(Mzon)
      Dimensiondtau(Mzon,0:Np)
      Real*4xipl(0:Np),fspl(0:Np),ftst(0:Np),fmin,fmax
      DimensionZR(0:Mzon)
      DimensionRM(0:Mzon),umr(0:Mzon)
      DimensionRHS(2*Mzon+2)
      DimensionAmu(0:NP+1,0:Mzon)
      DimensionFSdir(0:NP+1,Mzon)
      DimensionKz(0:NP+1),Krowst(0:NP+1)
      DimensionNMU(Mzon)
      DimensionYe(Mzon)
      DimensionHAPW(Mzon,Nfrgam)
      DimensionHAPabW(Mzon,Nfrgam)
      DimensionHAPM(Mzon),HAPabM(Mzon),HAPabZ(Mzon)
      DimensionHAPZ(Mzon)
      DimensionTAUGAM(Mzon)
      DimensionChim(Mzon),Chiabm(Mzon),ChiabZ(Mzon)
      DimensionChiZ(Mzon)
      Realtime1,time2
      Realtm1,tm2
      LogicalScatG
      Parameter(Nchn=4)
      DataScatG/.False./
      If(toldg.GT.0.d0.AND.t.GT.toldg*1.003d0)then
      DO09997km=1,Nzon
      FJgam(km,1)=Fjgam(km,2)
09997 CONTINUE
      toldg=tnewg
      Ngamma=2
      Else
      toldg=t
      Ngamma=2
      endif
      DO09994Igamma=2,Ngamma,-1
      If(Igamma.EQ.1)Then
      Homo=0.d0
      DO09991km=1,Nzon
      Homo=Homo+(t-toldg)*ABS(Uy(km))/Ry(km)*dm(km)/(Amout-Amini)
09991 CONTINUE
      Homo=1.d0+Homo
      Else
      Homo=1.d0
      Endif
      DO09988k=1,nzon
      Ye(k)=0.d0
      DO09985i=1,Natom
      Ye(k)=Ye(k)+Zn(i)*Yabun(i,k)
09985 CONTINUE
09988 CONTINUE
      incnd=0
      DO09982k=nzon,2,-1
      taugam(k)=Capgam*Ye(k)*(UR*URHO)*RHO(k)*(RY(K)-RY(k-1))
      if(taugam(k).GT.30.D0.AND.incnd.EQ.0)incnd=k
09982 CONTINUE
      Rout=Homo*Ry(Nzon)
      Rcore=Homo*Ry(max(Kmnick,1))
      NPE=15*nint((Rout-Rcore)/Rout)
      NPE=min(NPE,15)
      NPE=max(NPE,2)
      NPC=15+15-NPE
      Pray(0)=0.D0
      Pray(NP+1)=ROUT
      DPE=(Rout-Rcore)/DBLE(NPE+1)
      DPC=Rcore/DBLE(15)
      DO09979i=1,15
      Pray(i)=Pray(i-1)+DPC
09979 CONTINUE
      DO09976i=15+1,Np
      Pray(i)=Pray(i-1)+DPE
09976 CONTINUE
      DO09973K=incnd+1,Nzon
      IF(K.GT.1)RM(K)=0.5D0*Homo*(Ry(K)+Ry(K-1))
      DO09970Lfr=1,Nfrgam
      HAPW(K,Lfr)=Capgam*Ye(k)*(UR*URHO)
      HAPabW(K,Lfr)=Capgam*Ye(k)*(UR*URHO)
09970 CONTINUE
09973 CONTINUE
      RM(1)=0.5D0*Homo*Ry(1)
      RM(0)=0.25D0*Homo*Ry(1)
      NEEDBR=.True.
      DO09967Lfr=1,Nfrgam
      Knth=incnd
      If(Knth.EQ.0)Then
      Rleft=0.d0
      else
      If(Knth.EQ.incnd)Then
      Rleft=Homo*Rcore
      else
      Rleft=Homo*Ry(Knth)
      endif
      endif
      KLASTS=Nzon
      DO09964Ip=NP,0,-1
      Kzer=Nzon
09961 IF(.NOT.(Pray(Ip).LT.RM(Kzer).AND.Kzer.GT.Knth))GOTO09960
      Kzer=Kzer-1
      GOTO09961
09960 CONTINUE
      Nrdial=max(Nzon-Kzer,1)
      DO09958K=Kzer+1,Nzon
      Amu(Ip,K)=SQRT(1.D0-(Pray(Ip)/RM(K))**2)
09958 CONTINUE
      Amu(Ip,Kzer)=0.d0
      K=Kzer
      If(K.LT.KlastS)then
      DO09955IK=K+1,KlastS
      NMU(IK)=Ip
09955 CONTINUE
      KlastS=K
      Elseif(K.GT.0)then
      Nmu(K)=15
      Endif
      Kz(Ip)=Kzer
09964 CONTINUE
      Krow=0
      Krowst(Np)=0
      DO09952Ip=NP,0,-1
      Kzer=Kz(Ip)
09952 CONTINUE
      KZrowsc=Krow
      If(ScatG)then
      Write(*,*)' Scat gdepos6'
      NEQ=KZrowsc+(Nzon-Knth)
      else
      NEQ=krow
      endif
      If(KNadap.EQ.2.or.KNadap.EQ.3)then
      write(*,*)' freqs not geom. progr.!! '
      stop52
      endif
      zerfr=log(freqmn(1))+1.d0/dlognu(1)
      DO09949Kpl=Nzon,incnd+1,-1
      DO09946Ip=Nmu(Kpl),0,-1
      fr0=freqmn(Lfr)
      chiab=HAPabW(Kpl,Lfr)
      chiex=HAPW(Kpl,Lfr)
      dtau(Kpl,Ip)=(Amu(Ip,Kpl)*RM(Kpl)-Amu(Ip,Kpl-1)*RM(Kpl-1))*chiex*rho(Kpl)
      If(ScatG.AND.Nstep.GT.1)then
      fdirsumm=(chiab)
      elseif(KNadap.LT.0)then
      fdirsumm=XNifor(Kpl)*(1.d0-exp(-dtau(Kpl,Ip)/2.d0))
      else
      fdirsumm=(1.d0-exp(-dtau(Kpl,Ip)/2.d0))
      endif
      tauz=dtau(Kpl,Ip)/2.d0
      K=Kpl-1
09943 IF(.NOT.(K.GT.Kz(Ip)))GOTO09942
      chiab=HAPabW(K,Lfr)
      chiex=HAPW(K,Lfr)
      dtau(K,Ip)=(Amu(Ip,K)*RM(K)-Amu(Ip,K-1)*RM(K-1))*chiex*rho(K)
      If(ScatG.AND.Nstep.GT.1)then
      fdirsumm=fdirsumm+(chiab)
      elseif(KNadap.LT.0)then
      fdirsumm=fdirsumm+XNifor(K)*exp(-tauz)*(1.d0-exp(-dtau(K,Ip)))
      else
      fdirsumm=fdirsumm+exp(-tauz)*(1.d0-exp(-dtau(K,Ip)))
      endif
      tauz=tauz+dtau(K,Ip)
      K=K-1
      GOTO09943
09942 CONTINUE
      if(K.EQ.Kz(ip).AND.tauz.LT.1.d+02)then
09940 IF(.NOT.(tauz.LT.1.d+02.AND.K.LT.Nzon))GOTO09939
      K=K+1
      chiab=HAPabW(K,Lfr)
      chiex=HAPW(K,Lfr)
      dtau(K,Ip)=(Amu(Ip,K)*RM(K)-Amu(Ip,K-1)*RM(K-1))*chiex*rho(K)
      If(ScatG.AND.Nstep.GT.1)then
      tauz=tauz+dtau(K,Ip)
      fdirsumm=fdirsumm+(chiab)
      elseif(KNadap.LT.0)then
      tauz=tauz+dtau(K,Ip)
      fdirsumm=fdirsumm+XNifor(K)*exp(-tauz)*(1.d0-exp(-dtau(K,Ip)))
      else
      tauz=tauz+dtau(K,Ip)
      fdirsumm=fdirsumm+exp(-tauz)*(1.d0-exp(-dtau(K,Ip)))
      endif
      GOTO09940
09939 CONTINUE
      endif
      If(Kpl.GT.kz(ip))then
      FSdir(Ip,Kpl)=fdirsumm
      endif
09946 CONTINUE
09999 continue
09949 CONTINUE
      DO09937Kpl=incnd+1,Nzon
      DO09934Ip=Nmu(Kpl),0,-1
      Ki=max(Kpl,kz(Ip)+1)
      fr0=freqmn(Lfr)
      chiab=HAPabW(Ki,Lfr)
      chiex=HAPW(Ki,Lfr)
      dtau(Ki,Ip)=(Amu(Ip,Ki)*RM(Ki)-Amu(Ip,Ki-1)*RM(Ki-1))*chiex*rho(Ki)
      If(ScatG.AND.Nstep.GT.1)then
      fdirsumm=(chiab)
      elseif(KNadap.LT.0)then
      fdirsumm=XNifor(Ki)*(1.d0-exp(-dtau(Ki,Ip)/2.d0))
      else
      fdirsumm=(1.d0-exp(-dtau(Ki,Ip)/2.d0))
      endif
      tauz=dtau(Ki,Ip)/2.d0
      K=Ki
09931 IF(.NOT.(K.LT.Nzon))GOTO09930
      K=K+1
      chiab=HAPabW(K,Lfr)
      chiex=HAPW(K,Lfr)
      dtau(K,Ip)=(Amu(Ip,K)*RM(K)-Amu(Ip,K-1)*RM(K-1))*chiex*rho(K)
      If(ScatG.AND.Nstep.GT.1)then
      fdirsumm=fdirsumm+(chiab)
      elseif(KNadap.LT.0)then
      fdirsumm=fdirsumm+exp(-tauz)*XNifor(K)*(1.d0-exp(-dtau(K,Ip)))
      else
      fdirsumm=fdirsumm+exp(-tauz)*(1.d0-exp(-dtau(K,Ip)))
      endif
      tauz=tauz+dtau(K,Ip)
      GOTO09931
09930 CONTINUE
      If(Kpl.GT.kz(ip))then
      FSdir(Ip,Kpl)=(FSdir(Ip,Kpl)+fdirsumm)/2.d0
      endif
09934 CONTINUE
      DO09928Ip=0,NP
      xipl(Ip)=(Ip)
      If(Kpl.LE.kz(ip))then
      ftst(Ip)=ftst(max(0,Ip-1))
      fspl(Ip)=fspl(max(0,Ip-1))
      endif
09928 CONTINUE
09998 continue
09937 CONTINUE
      DO09925Ip=0,Np
      fcom(Ip,Lfr)=2.d0*FSdir(Ip,Nzon)
09925 CONTINUE
      DO09922K=1,Nzon
      If(K.LE.Knth)Then
      If(Knadap.LT.0)Then
      FJgam(k,2)=XNIfor(K)
      Else
      FJgam(k,2)=1.D0
      Endif
      Else
      FJgam(k,2)=0.D0
      DO09919Isw=NMU(K)-1,0,-1
      FJgam(k,2)=FJgam(k,2)+(FSdir(Isw,K)+FSdir(Isw+1,K))*(Amu(Isw,K)-Amu(Isw+1,K))
09919 CONTINUE
      FJgam(k,2)=FJgam(k,2)+2.D0*FSdir(NMU(K),K)*Amu(NMU(K),K)
      FJgam(k,2)=FJgam(k,2)*0.5D0
      endif
09922 CONTINUE
      IF(MOD(Nstep,900).EQ.0)THEN
      WRITE(4,'(''  K/   FJgam:'')')
      WRITE(4,'(8(1X,I3,''->'',1P,E9.2))')(K,FJgam(K,2),K=incnd+1,Nzon)
      ENDIF
09967 CONTINUE
09994 CONTINUE
      tnewg=t
      RETURN
      END
