#!/usr/bin/env bash


function do_one_oplib { 
        echo "using" $1
        echo
        check_okay
        cd kap_input_data/oplib/
        check_okay
        python spline_OPLIB_tables.py $1 
        check_okay   
        echo $1_spline
        check_okay
        cp -r $1_spline/* ../../data/kap_data/.
        check_okay
        rm -rf $1_spline
        check_okay
        cd ../..
        check_okay
        echo 'done' $1
        echo
}


do_one_oplib kap_input_data/oplib/OPLIB_GS98_LOG_1194_25E
do_one_oplib kap_input_data/oplib/OPLIB_AGSS09_LOG_1194_25E
do_one_oplib kap_input_data/oplib/OPLIB_AAG21_LOG_1194_25E
do_one_oplib kap_input_data/oplib/OPLIB_MB22_LOG_1194_25E


echo "**************************"
echo "**************************"
echo "done building oplib tables"
echo "**************************"
echo "**************************"
