#!/bin/bash

sed 's/log_center_density_limit/log_center_density_upper_limit/' -i inlist*
sed 's/log_center_temp_limit/log_center_temp_upper_limit/' -i inlist*
sed 's/center_entropy_limit/center_entropy_upper_limit/' -i inlist*
sed 's/max_entropy_limit/max_entropy_upper_limit/' -i inlist*
sed -E '/inlist[1-5]/s/([1-5])([_a-z]*) =/\2\(\1\) =/' -i inlist*
