#!/bin/bash

do_one(){
    ln -sf inlists/inlist_$1 inlist_equations
    ln -sf inlists/inlist_$2 inlist_resolution
    ./rn
    mv LOGS/history.data LOGS/$1-$2.data
    mv final_profile.data LOGS/$1-$2.profile
}


do_set(){
    do_one $1 lr
    do_one $1 mr
    do_one $1 hr
#    do_one $1 ur
}

do_set dedt_total
do_set eps_grav
do_set eps_grav_future

