#!/bin/bash

# uncomment the following line to skip the optional inlists
# MESA_SKIP_OPTIONAL=t

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
if [ -n "$MESA_SKIP_OPTIONAL" ]; then
    cp standard_end_core_he_burn.mod end_core_he_burn.mod
else
    do_one inlist_initial_header end_core_he_burn.mod
    cp end_core_he_burn.mod standard_end_core_he_burn.mod
fi

do_one inlist_cburn_inward_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'



