#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_near_zams.mod near_zams.mod
else
   do_one inlist_to_zams_header near_zams.mod
   cp near_zams.mod standard_near_zams.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_ready_to_remove.mod ready_to_remove.mod
else
   do_one inlist_before_remove_header ready_to_remove.mod
   cp ready_to_remove.mod standard_ready_to_remove.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_removed.mod removed.mod
else
   do_one inlist_remove_header removed.mod
   cp removed.mod standard_removed.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_ready.mod ready.mod
else
   do_one inlist_after_remove_header ready.mod
   cp ready.mod standard_ready.mod
fi

if [ -n "$MESA_SKIP_OPTIONAL" ]; then
   cp standard_before_si_burn.mod before_si_burn.mod
else
   do_one inlist_to_pre_si_burn_header before_si_burn.mod
   cp before_si_burn.mod standard_before_si_burn.mod
fi

do_one inlist_to_cc_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for make_pre_ccsn_13bvn'

