---
name: 'install-mesa'

description: 'Download and install the MESA SDK and install MESA'

inputs:
  sdk:
    description: 'The version of the MESA SDK to install'
    required: false
    default: '23.7.3'


runs:

  using: 'composite'

  steps:
    - name: Install SDK Linux
      if: ${{ (runner.os == 'Linux') }}
      uses: ./.github/actions/install-sdk-linux
      with:
        sdk: ${{inputs.sdk}}

    - name: Install SDK Linux
      if: ${{ (runner.os == 'Macos') }}
      uses: ./.github/actions/install-sdk-macos
      with:
        sdk: ${{inputs.sdk}}

    - name: Create LFS file list
      run: |
        git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      uses: actions/cache@v4
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      run: git lfs pull
      shell: bash
      if: steps.lfs-cache.outputs.cache-hit != 'true'

    - name: Git LFS Checkout
      run: git lfs checkout
      shell: bash
      if: steps.lfs-cache.outputs.cache-hit == 'true'

    - name: Set MESA environment variables
      shell: bash
      run: |
        echo "MESA_DIR=$PWD" >> $GITHUB_ENV

    - name: Setup environment Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        # Linux runners have 4 cores
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        echo "OMP_NUM_THREADS=4" >> $GITHUB_ENV
        echo "NPROCS=4" >> $GITHUB_ENV
        echo "SED=sed" >> $GITHUB_ENV

    - name: Setup environment MacOS
      shell: bash
      if: runner.os == 'macOS'
      run: |
        # MacOS runners have 3 cores
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        echo "OMP_NUM_THREADS=3" >> $GITHUB_ENV
        echo "NPROCS=3" >> $GITHUB_ENV
        echo "SED=gsed" >> $GITHUB_ENV

    - name: Compile
      run: |
        source "${MESASDK_ROOT}/bin/mesasdk_init.sh"
        # Everything is run as root so we need to disable the root check in the install script
        $SED -i 's/\${EUID:-\$(id -u)}/1/' install
        # Turn off caching during build to save more space
        $SED -i 's/use_cache_for_eos = .true./use_cache_for_eos = .false./g' $MESA_DIR/eos/public/eos_def.f90
        $SED -i 's/use_cache = .true./use_cache = .false./g' $MESA_DIR/star/private/star_private_def.f90
        ./install
      shell: bash
