#!/bin/bash

function error {
	echo
	cat diff.txt
	echo
	pwd
	echo "TEST FAILED -- compare obs.txt to obs.test.txt"
	echo
	exit 1
}

function enum_procs {
    if [ -n "$NPROCS" ]; then
        echo $NPROCS
    else
        case $(uname -s) in
            Linux)
                if [ -r /proc/cpuinfo ]; then
                    grep -c processor /proc/cpuinfo
                else
                    echo 1
                fi
                ;;
            Darwin)
                sysctl hw.ncpu | awk '{print $2}'
                ;;
            *)
            echo 1
            ;;
        esac
    fi
}

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

if [ ! -f ../skip_build ] 
then
	if [ ! -f skip_build ]
	then
  		cd make
  		make -j$(enum_procs)
  		check_okay
  		cd ..
	fi
fi

if [ ! -f ../skip_test ]
then
	if [ ! -f skip_test ]  && [ ! -f test/build_skip_test ]
	then
    	cd test
  		./ck >& diff.txt
  		if [ $? -eq 0 ]
  		then
  			if [ -s diff.txt ]
  			then
            grep -vq IEEE_ diff.txt
            if [ $? -eq 0 ]
            then
            # This matches if we have any error and no IEEE_ errors or
            # we have an IEEE_ error and any other error
            # but does not match if we only have IEEE_ errors
               error
            fi
  			fi
  		else
  			error
  		fi
	fi
fi
