#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

   do_one inlist_make_late_pre_zams_header late_pre_zams.mod
   cp late_pre_zams.mod standard_late_pre_zams.mod
   do_one inlist_to_zams_header zams.mod
   cp zams.mod standard_zams.mod
   do_one inlist_to_near_end_core_he_burn_header near_end_core_he_burn.mod
   cp near_end_core_he_burn.mod standard_near_end_core_he_burn.mod
   do_one inlist_to_end_core_c_burn_header after_core_c_burn.mod
   cp after_core_c_burn.mod standard_after_core_c_burn.mod
#   do_one inlist_to_lgTmax_9.5_header lgTmax_9.5.mod
#   cp lgTmax_9.5.mod standard_lgTmax_9.5.mod   
#   do_one inlist_to_cc_header start_core_collapse.mod

do_one inlist_to_gamma1_limit_header gamma1_limit.mod
do_one inlist_finish_core_collapse_header final.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

