name: Build on Linux with SDK

on: [pull_request, release]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sdk: ["21.4.1", "22.6.1", "23.7.3"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MESA on ${{ runner.os }} with SDK ${{matrix.sdk}}
        uses: ./.github/actions/install-mesa
        with:
          sdk: ${{matrix.sdk}}
