---
name: Build on Linux with SDK

on:
  workflow_dispatch:
  release:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    if: |
      !(github.event_name == 'pull_request' && ${{ contains(github.event.commits[0].message, 'ci skip') }})
    strategy:
      fail-fast: false
      matrix:
        sdk: ["22.6.1", "23.7.3", "24.7.1"]  # pick 2 or 3 most recent.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MESA on ${{ runner.os }} with SDK ${{matrix.sdk}}
        uses: ./.github/actions/install-mesa
        with:
          sdk: ${{matrix.sdk}}
