---
name: Code Coverage

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  run-code-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name : Install lcov
        run: |
          sudo apt-get -y update
          sudo apt-get -y install lcov
        shell: bash

      - name: Tweak install script to link gcov
        run: |
          cd $GITHUB_WORKSPACE
          sed -i 's/FC = gfortran/FC = gfortran -fprofile-arcs -ftest-coverage -lgcov --coverage/' install
        shell: bash

      - name: Install MESA on ${{ runner.os }} with SDK 24.7.1
        uses: ./.github/actions/install-mesa
        with:
          sdk: "24.7.1"

      - name: Run gcov
        run: |
          gcov */*/*.gcno */*/*/*.gcno 
        shell: bash

      - name: Generate html with lcov
        run: |
          genhtml --ignore-errors missing,missing  --ignore-errors empty,empty  --filter missing --output-directory .htmlcov  coverage.info
          lcov --gcov-tool gcov --ignore-errors negative,inconsistent --capture --directory . --output-file coverage.info
        shell: bash

      - name: Save the html folder as an artifact
        uses: actions/upload-artifact@v2
        with: 
          path: './htmlcov/'
      
      - name: Deploy to Github Pages
          uses: actions/deploy-pages@v4
          id: deployment
