name: Test Mesa

on: [pull_request, release]

jobs:
  test_mesa:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MESA on ${{ runner.os }} with SDK 23.7.3
        uses: ./.github/actions/install-mesa
        with:
          sdk: "23.7.3"

      - name: Checkout mesa_test
        uses: actions/checkout@v4
        with:
          repository: MESAHub/mesa_test
          path: mesa_test # Store in $GITHUB_WORKSPACE/mesa_test

      - name: Install mesa_test
        run: |
          cd
          pwd
          ls -la
          cd $GITHUB_WORKSPACE/mesa_test
          sudo gem install mesa_test
          cd $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          mkdir .mesa_test
          pwd
          echo "XXX"
          ls -la ../..
          echo "XXX"
          ls -la ..
          echo "XXX"
          ls -la
          echo "XXX"
          ls -la mesa_test
          echo "XXX"
        shell: bash

      - name: Create config file
        run: |
          MESA_TEST_YML=$GITHUB_WORKSPACE/.mesa_test/config.yml
          echo "---" > $MESA_TEST_YML
          echo "computer_name: GitHub_Runner" >> $MESA_TEST_YML
          echo "email: ${{ secrets.MESA_TEST_EMAIL }}" >> $MESA_TEST_YML
          echo "password: ${{ secrets.MESA_TEST_PASSWORD }}" >> $MESA_TEST_YML
          echo "logs_token: ${{ secrets.MESA_TEST_LOGS_TOKEN }}" >> $MESA_TEST_YML
          echo "github_protocol: :ssh" >> $MESA_TEST_YML
          echo "mesa_mirror: $GITHUB_WORKSPACE/mirror" >> $MESA_TEST_YML
          echo "mesa_work: $GITHUB_WORKSPACE" >> $MESA_TEST_YML
          echo "platform: Linux" >> $MESA_TEST_YML
          echo "platform_version: Ubuntu" >> $MESA_TEST_YML
          mesa_test install --no-checkout
          mesa_test submit --empty
        shell: bash

      #- name: Test Problem 13
      #  run: |
      #    mesa_test test 13
      #  shell: bash

      #- name: Test Problem 15
      #  run: |
      #    mesa_test test 15
      #  shell: bash
      #  
      #- name: Test Problem 29
      #  run: |
      #    mesa_test test 29
      #  shell: bash

      #- name: Test Problem 41
      #  run: |
      #    mesa_test test 41
      #  shell: bash
