name: Test Mesa

on: [pull_request, release]

jobs:
  test_mesa:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Install MESA on ${{ runner.os }} with SDK 23.7.3
      #  uses: ./.github/actions/install-mesa
      #  with:
      #    sdk: "23.7.3"
      # XXX    do_install: "false" # Skip install because mesa_test will do this

      - name: Checkout mesa_test
        uses: actions/checkout@v4
        with:
          repository: MESAHub/mesa_test
          path: mesa_test # Store in $GITHUB_WORKSPACE/mesa_test

      - name: Install mesa_test
        run: |
          # Setup mesa_test
          cd $GITHUB_WORKSPACE/mesa_test
          sudo gem install mesa_test
          cd $GITHUB_WORKSPACE
          mkdir /home/runner/.mesa_test
        shell: bash

      - name: Create mesa_test config file
        env:
          MESA_TEST_EMAIL: ${{ secrets.MESA_TEST_EMAIL }}
          MESA_TEST_PASSWORD: ${{ secrets.MESA_TEST_PASSWORD }}
          MESA_TEST_LOGS_TOKEN: ${{ secrets.MESA_TEST_LOGS_TOKEN }}
        run: |
          import os
          lines = ['---', 'computer_name: GitHub_Runner', 'email: '+os.getenv("MESA_TEST_EMAIL"), 'password: '+os.getenv("MESA_TEST_PASSWORD"), 'logs_token: '+os.getenv("MESA_TEST_LOGS_TOKEN"), 'github_protocol: :ssh', 'mesa_mirror: '+os.getenv("GITHUB_WORKSPACE")+'/mirror', 'mesa_work: '+os.getenv("GITHUB_WORKSPACE"), 'platform: Linux', 'platform_version: Ubuntu']
          with open('/home/runner/.mesa_test/config.yml', 'a') as f:
            f.writelines(lines)
        shell: python

      - name: Test Problem 13
        run: |
          mesa_test submit --empty
          # XXXmesa_test test 13
        shell: bash

      #- name: Test Problem 15
      #  run: |
      #    mesa_test test 15
      #  shell: bash
      #  
      #- name: Test Problem 29
      #  run: |
      #    mesa_test test 29
      #  shell: bash

      #- name: Test Problem 41
      #  run: |
      #    mesa_test test 41
      #  shell: bash
